// 20200422150458
// http://api.data.go.kr/openapi/child-prtc-zn-std?pageNo=1&numOfRows=10&type=json&insttNm=%EC%84%9C%EC%9A%B8%ED%8A%B9%EB%B3%84%EC%8B%9C%20%EA%B0%95%EC%84%9C%EA%B5%AC&ServiceKey=skXA159lQs%2FIrfBwdy5vEAZdR4E3Pfrjz%2BMhGc8Od%2FCV7ODFqkaAczjP9yzdfvDw1SEj0PxrvLdE9U9Gf2KYgw%3D%3D

var data = {
  "response": {
    "header": {
      "resultCode": "00",
      "resultMsg": "NORMAL_SERVICE",
      "type": "json"
    },
    "body": {
      "items": [
        {
          "fcltyKnd": "초등학교",
          "trgetFcltyNm": "가곡초등학교",
          "rdnmadr": "서울특별시 강서구 공항대로36길 74 (내발산동)",
          "lnmadr": "null",
          "latitude": "37.5557076",
          "hardness": "126.8361018",
          "longitude": "126.8361018",
          "institutionNm": "서울특별시 강서구청",
          "cmptncPolcsttnNm": "강서경찰서",
          "cctvYn": "Y",
          "cctvNumber": "1",
          "prtcareaRw": "4",
          "referenceDate": "2020-01-01",
          "insttCode": "3150000",
          "insttNm": "서울특별시 강서구"
        },
        {
          "fcltyKnd": "초등학교",
          "trgetFcltyNm": "발산초등학교",
          "rdnmadr": "서울특별시 강서구 강서로45길 113 (내발산동)",
          "lnmadr": "null",
          "latitude": "37.5502619848",
          "hardness": "126.8309941522",
          "longitude": "126.8309941522",
          "institutionNm": "서울특별시 강서구청",
          "cmptncPolcsttnNm": "강서경찰서",
          "cctvYn": "Y",
          "cctvNumber": "2",
          "prtcareaRw": "10",
          "referenceDate": "2020-01-01",
          "insttCode": "3150000",
          "insttNm": "서울특별시 강서구"
        },
        {
          "fcltyKnd": "초등학교",
          "trgetFcltyNm": "방화초등학교",
          "rdnmadr": "서울특별시 강서구 양천로6길 92 (방화동)",
          "lnmadr": "null",
          "latitude": "37.56870364",
          "hardness": "126.8074988",
          "longitude": "126.8074988",
          "institutionNm": "서울특별시 강서구청",
          "cmptncPolcsttnNm": "강서경찰서",
          "cctvYn": "Y",
          "cctvNumber": "1",
          "prtcareaRw": "10",
          "referenceDate": "2020-01-01",
          "insttCode": "3150000",
          "insttNm": "서울특별시 강서구"
        },
        {
          "fcltyKnd": "초등학교",
          "trgetFcltyNm": "백석초등학교",
          "rdnmadr": "서울특별시 강서구 공항대로 491 (등촌동)",
          "lnmadr": "null",
          "latitude": "37.5536472918",
          "hardness": "126.8624252813",
          "longitude": "126.8624252813",
          "institutionNm": "서울특별시 강서구청",
          "cmptncPolcsttnNm": "강서경찰서",
          "cctvYn": "Y",
          "cctvNumber": "1",
          "prtcareaRw": "6",
          "referenceDate": "2020-01-01",
          "insttCode": "3150000",
          "insttNm": "서울특별시 강서구"
        },
        {
          "fcltyKnd": "초등학교",
          "trgetFcltyNm": "삼정초등학교",
          "rdnmadr": "서울특별시 강서구 금낭화로 222 (방화동)",
          "lnmadr": "null",
          "latitude": "37.5805078932",
          "hardness": "126.8104934611",
          "longitude": "126.8104934611",
          "institutionNm": "서울특별시 강서구청",
          "cmptncPolcsttnNm": "강서경찰서",
          "cctvYn": "Y",
          "cctvNumber": "1",
          "prtcareaRw": "18",
          "referenceDate": "2020-01-01",
          "insttCode": "3150000",
          "insttNm": "서울특별시 강서구"
        },
        {
          "fcltyKnd": "초등학교",
          "trgetFcltyNm": "신곡초등학교",
          "rdnmadr": "서울특별시 강서구 등촌로13자길 42-14 (화곡동)",
          "lnmadr": "null",
          "latitude": "37.5390734",
          "hardness": "126.8560116089",
          "longitude": "126.8560116089",
          "institutionNm": "서울특별시 강서구청",
          "cmptncPolcsttnNm": "강서경찰서",
          "cctvYn": "Y",
          "cctvNumber": "1",
          "prtcareaRw": "6",
          "referenceDate": "2020-01-01",
          "insttCode": "3150000",
          "insttNm": "서울특별시 강서구"
        },
        {
          "fcltyKnd": "초등학교",
          "trgetFcltyNm": "정곡초등학교",
          "rdnmadr": "서울특별시 강서구 방화대로50길 22 (방화동)",
          "lnmadr": "null",
          "latitude": "37.5769308",
          "hardness": "126.818936",
          "longitude": "126.818936",
          "institutionNm": "서울특별시 강서구청",
          "cmptncPolcsttnNm": "강서경찰서",
          "cctvYn": "Y",
          "cctvNumber": "1",
          "prtcareaRw": "20",
          "referenceDate": "2020-01-01",
          "insttCode": "3150000",
          "insttNm": "서울특별시 강서구"
        },
        {
          "fcltyKnd": "유치원",
          "trgetFcltyNm": "정곡초등학교(병설유치원)",
          "rdnmadr": "서울특별시 강서구 방화대로50길 22 (방화동)",
          "lnmadr": "null",
          "latitude": "37.5769308",
          "hardness": "126.818936",
          "longitude": "126.818936",
          "institutionNm": "서울특별시 강서구청",
          "cmptncPolcsttnNm": "강서경찰서",
          "cctvYn": "N",
          "cctvNumber": "null",
          "prtcareaRw": "null",
          "referenceDate": "2020-01-01",
          "insttCode": "3150000",
          "insttNm": "서울특별시 강서구"
        },
        {
          "fcltyKnd": "초등학교",
          "trgetFcltyNm": "치현초등학교",
          "rdnmadr": "서울특별시 강서구 방화대로47길 43 (방화동)",
          "lnmadr": "null",
          "latitude": "37.5759194191",
          "hardness": "126.814673",
          "longitude": "126.814673",
          "institutionNm": "서울특별시 강서구청",
          "cmptncPolcsttnNm": "강서경찰서",
          "cctvYn": "Y",
          "cctvNumber": "2",
          "prtcareaRw": "10",
          "referenceDate": "2020-01-01",
          "insttCode": "3150000",
          "insttNm": "서울특별시 강서구"
        },
        {
          "fcltyKnd": "유치원",
          "trgetFcltyNm": "공진초등학교병설유치원",
          "rdnmadr": "서울특별시 강서구 마곡서로 33 (마곡동)",
          "lnmadr": "null",
          "latitude": "37.557822",
          "hardness": "126.822611",
          "longitude": "126.822611",
          "institutionNm": "서울특별시 강서구청",
          "cmptncPolcsttnNm": "강서경찰서",
          "cctvYn": "N",
          "cctvNumber": "null",
          "prtcareaRw": "null",
          "referenceDate": "2020-01-01",
          "insttCode": "3150000",
          "insttNm": "서울특별시 강서구"
        },
        {
          "fcltyKnd": "유치원",
          "trgetFcltyNm": "돌샘유치원",
          "rdnmadr": "서울특별시 강남구 개포로 516",
          "lnmadr": "null",
          "latitude": "37.4891403199",
          "hardness": "127.0708697840",
          "longitude": "127.0708697840",
          "institutionNm": "서울특별시 강남구청",
          "cmptncPolcsttnNm": "수서경찰서",
          "cctvYn": "Y",
          "cctvNumber": "1",
          "prtcareaRw": "12.6",
          "referenceDate": "2019-12-20",
          "insttCode": "3220000",
          "insttNm": "서울특별시 강남구"
        },
        {
          "fcltyKnd": "유치원",
          "trgetFcltyNm": "신양유치원",
          "rdnmadr": "서울특별시 강남구 선릉로10길 18-6",
          "lnmadr": "null",
          "latitude": "37.483431",
          "hardness": "127.061678",
          "longitude": "127.061678",
          "institutionNm": "서울특별시 강남구청",
          "cmptncPolcsttnNm": "수서경찰서",
          "cctvYn": "Y",
          "cctvNumber": "2",
          "prtcareaRw": "6",
          "referenceDate": "2019-12-20",
          "insttCode": "3220000",
          "insttNm": "서울특별시 강남구"
        },
        {
          "fcltyKnd": "유치원",
          "trgetFcltyNm": "이화유치원",
          "rdnmadr": "서울특별시 강남구 개포로109길 9",
          "lnmadr": "null",
          "latitude": "37.495751",
          "hardness": "127.075096",
          "longitude": "127.075096",
          "institutionNm": "서울특별시 강남구청",
          "cmptncPolcsttnNm": "수서경찰서",
          "cctvYn": "Y",
          "cctvNumber": "2",
          "prtcareaRw": "15",
          "referenceDate": "2019-12-20",
          "insttCode": "3220000",
          "insttNm": "서울특별시 강남구"
        },
        {
          "fcltyKnd": "유치원",
          "trgetFcltyNm": "영동제일유치원",
          "rdnmadr": "서울특별시 강남구 삼성로120길 28",
          "lnmadr": "null",
          "latitude": "37.517579",
          "hardness": "127.053437",
          "longitude": "127.053437",
          "institutionNm": "서울특별시 강남구청",
          "cmptncPolcsttnNm": "강남경찰서",
          "cctvYn": "Y",
          "cctvNumber": "2",
          "prtcareaRw": "5.8",
          "referenceDate": "2019-12-20",
          "insttCode": "3220000",
          "insttNm": "서울특별시 강남구"
        },
        {
          "fcltyKnd": "유치원",
          "trgetFcltyNm": "소망유치원",
          "rdnmadr": "서울특별시 강남구 광평로56길 11",
          "lnmadr": "null",
          "latitude": "37.4879790845",
          "hardness": "127.1056313773",
          "longitude": "127.1056313773",
          "institutionNm": "서울특별시 강남구청",
          "cmptncPolcsttnNm": "수서경찰서",
          "cctvYn": "Y",
          "cctvNumber": "1",
          "prtcareaRw": "11",
          "referenceDate": "2019-12-20",
          "insttCode": "3220000",
          "insttNm": "서울특별시 강남구"
        },
        {
          "fcltyKnd": "유치원",
          "trgetFcltyNm": "청운유치원",
          "rdnmadr": "서울특별시 강남구 언주로65길 5",
          "lnmadr": "null",
          "latitude": "37.4950489901",
          "hardness": "127.045531",
          "longitude": "127.045531",
          "institutionNm": "서울특별시 강남구청",
          "cmptncPolcsttnNm": "수서경찰서",
          "cctvYn": "Y",
          "cctvNumber": "1",
          "prtcareaRw": "11.5",
          "referenceDate": "2019-12-20",
          "insttCode": "3220000",
          "insttNm": "서울특별시 강남구"
        },
        {
          "fcltyKnd": "유치원",
          "trgetFcltyNm": "묘동유치원",
          "rdnmadr": "서울특별시 강남구 도곡로78길 8",
          "lnmadr": "null",
          "latitude": "37.4974073916",
          "hardness": "127.058723",
          "longitude": "127.058723",
          "institutionNm": "서울특별시 강남구청",
          "cmptncPolcsttnNm": "수서경찰서",
          "cctvYn": "Y",
          "cctvNumber": "5",
          "prtcareaRw": "5.5",
          "referenceDate": "2019-12-20",
          "insttCode": "3220000",
          "insttNm": "서울특별시 강남구"
        },
        {
          "fcltyKnd": "유치원",
          "trgetFcltyNm": "푸른유치원",
          "rdnmadr": "서울특별시 강남구 일원로14길 25",
          "lnmadr": "null",
          "latitude": "37.4847980900",
          "hardness": "127.0811004779",
          "longitude": "127.0811004779",
          "institutionNm": "서울특별시 강남구청",
          "cmptncPolcsttnNm": "수서경찰서",
          "cctvYn": "Y",
          "cctvNumber": "1",
          "prtcareaRw": "15.2",
          "referenceDate": "2019-12-20",
          "insttCode": "3220000",
          "insttNm": "서울특별시 강남구"
        },
        {
          "fcltyKnd": "유치원",
          "trgetFcltyNm": "성요셉유치원",
          "rdnmadr": "서울특별시 강남구 도산대로83길 27",
          "lnmadr": "null",
          "latitude": "37.5262731393",
          "hardness": "127.0482111685",
          "longitude": "127.0482111685",
          "institutionNm": "서울특별시 강남구청",
          "cmptncPolcsttnNm": "강남경찰서",
          "cctvYn": "Y",
          "cctvNumber": "2",
          "prtcareaRw": "5.9",
          "referenceDate": "2019-12-20",
          "insttCode": "3220000",
          "insttNm": "서울특별시 강남구"
        },
        {
          "fcltyKnd": "유치원",
          "trgetFcltyNm": "강남유치원",
          "rdnmadr": "서울특별시 강남구 선릉로129길 31",
          "lnmadr": "null",
          "latitude": "37.515448",
          "hardness": "127.039009",
          "longitude": "127.039009",
          "institutionNm": "서울특별시 강남구청",
          "cmptncPolcsttnNm": "강남경찰서",
          "cctvYn": "Y",
          "cctvNumber": "2",
          "prtcareaRw": "8.6",
          "referenceDate": "2019-12-20",
          "insttCode": "3220000",
          "insttNm": "서울특별시 강남구"
        }, //강남구
        {
          "fcltyKnd": "어린이집",
          "trgetFcltyNm": "KDB어린이집",
          "rdnmadr": "서울특별시 영등포구 은행로 14",
          "lnmadr": "서울특별시 영등포구 여의도동 16-3",
          "latitude": "37.527080",
          "hardness": "126.920824",
          "longitude": "126.920824",
          "institutionNm": "영등포구청",
          "cmptncPolcsttnNm": "영등포경찰서",
          "cctvYn": "Y",
          "cctvNumber": "1",
          "prtcareaRw": "22",
          "referenceDate": "2019-05-03",
          "insttCode": "3180000",
          "insttNm": "서울특별시 영등포구"
        },
        {
          "fcltyKnd": "어린이집",
          "trgetFcltyNm": "양평3가어린이집",
          "rdnmadr": "서울특별시 영등포구 선유서로34길 10",
          "lnmadr": "서울특별시 영등포구 양평동3가 36",
          "latitude": "37.526829",
          "hardness": "126.887360",
          "longitude": "126.887360",
          "institutionNm": "영등포구청",
          "cmptncPolcsttnNm": "영등포경찰서",
          "cctvYn": "Y",
          "cctvNumber": "1",
          "prtcareaRw": "7~9.5",
          "referenceDate": "2019-05-03",
          "insttCode": "3180000",
          "insttNm": "서울특별시 영등포구"
        },
        {
          "fcltyKnd": "어린이집",
          "trgetFcltyNm": "꿈나무어린이집",
          "rdnmadr": "서울특별시 영등포구 대방천로 199",
          "lnmadr": "서울특별시 영등포구 신길동 3741-18",
          "latitude": "37.498986",
          "hardness": "126.913041",
          "longitude": "126.913041",
          "institutionNm": "영등포구청",
          "cmptncPolcsttnNm": "영등포경찰서",
          "cctvYn": "Y",
          "cctvNumber": "1",
          "prtcareaRw": "7~9.5",
          "referenceDate": "2019-05-03",
          "insttCode": "3180000",
          "insttNm": "서울특별시 영등포구"
        },
        {
          "fcltyKnd": "어린이집",
          "trgetFcltyNm": "영신어린이집",
          "rdnmadr": "서울특별시 영등포구 신길로 132",
          "lnmadr": "서울특별시 영등포구 신길4동 239-6",
          "latitude": "37.503962",
          "hardness": "126.910783",
          "longitude": "126.910783",
          "institutionNm": "영등포구청",
          "cmptncPolcsttnNm": "영등포경찰서",
          "cctvYn": "Y",
          "cctvNumber": "1",
          "prtcareaRw": "20",
          "referenceDate": "2019-05-03",
          "insttCode": "3180000",
          "insttNm": "서울특별시 영등포구"
        },
        {
          "fcltyKnd": "어린이집",
          "trgetFcltyNm": "하나푸르니신길어린이집",
          "rdnmadr": "서울특별시 영등포구 신길로40길 5",
          "lnmadr": "서울특별시 영등포구 신길동 232-20",
          "latitude": "37.507080",
          "hardness": "126.911729",
          "longitude": "126.911729",
          "institutionNm": "영등포구청",
          "cmptncPolcsttnNm": "영등포경찰서",
          "cctvYn": "Y",
          "cctvNumber": "3",
          "prtcareaRw": "4",
          "referenceDate": "2019-05-03",
          "insttCode": "3180000",
          "insttNm": "서울특별시 영등포구"
        },
        {
          "fcltyKnd": "어린이집",
          "trgetFcltyNm": "하정어린이집",
          "rdnmadr": "서울특별시 영등포구 여의대방로 211",
          "lnmadr": "서울특별시 영등포구 신길7동 869",
          "latitude": "37.505832",
          "hardness": "126.922179",
          "longitude": "126.922179",
          "institutionNm": "영등포구청",
          "cmptncPolcsttnNm": "영등포경찰서",
          "cctvYn": "Y",
          "cctvNumber": "2",
          "prtcareaRw": "5~12",
          "referenceDate": "2019-05-03",
          "insttCode": "3180000",
          "insttNm": "서울특별시 영등포구"
        },
        {
          "fcltyKnd": "유치원",
          "trgetFcltyNm": "돈보스꼬유치원",
          "rdnmadr": "서울특별시 영등포구 도영로22길 22",
          "lnmadr": "서울특별시 영등포구 도림동 161",
          "latitude": "37.5105463373",
          "hardness": "126.9013855624",
          "longitude": "126.9013855624",
          "institutionNm": "영등포구청",
          "cmptncPolcsttnNm": "영등포경찰서",
          "cctvYn": "Y",
          "cctvNumber": "1",
          "prtcareaRw": "7~8",
          "referenceDate": "2019-05-03",
          "insttCode": "3180000",
          "insttNm": "서울특별시 영등포구"
        },
        {
          "fcltyKnd": "유치원",
          "trgetFcltyNm": "영은유치원",
          "rdnmadr": "서울특별시 영등포구 양산로 61",
          "lnmadr": "서울특별시 영등포구 양평동3가 8-2",
          "latitude": "37.525231",
          "hardness": "126.890011",
          "longitude": "126.890011",
          "institutionNm": "영등포구청",
          "cmptncPolcsttnNm": "영등포경찰서",
          "cctvYn": "Y",
          "cctvNumber": "1",
          "prtcareaRw": "4",
          "referenceDate": "2019-05-03",
          "insttCode": "3180000",
          "insttNm": "서울특별시 영등포구"
        },
        {
          "fcltyKnd": "유치원",
          "trgetFcltyNm": "윤중초등학교병설유치원",
          "rdnmadr": "서울특별시 영등포구 여의나루로2길 14",
          "lnmadr": "서울특별시 영등포구 여의도동 38",
          "latitude": "37.519747",
          "hardness": "126.922807",
          "longitude": "126.922807",
          "institutionNm": "영등포구청",
          "cmptncPolcsttnNm": "영등포경찰서",
          "cctvYn": "Y",
          "cctvNumber": "1",
          "prtcareaRw": "5~14",
          "referenceDate": "2019-05-03",
          "insttCode": "3180000",
          "insttNm": "서울특별시 영등포구"
        },
        {
          "fcltyKnd": "유치원",
          "trgetFcltyNm": "영중초등학교병설유치원",
          "rdnmadr": "서울특별시 영등포구 양산로 185",
          "lnmadr": "서울특별시 영등포구 영등포동7가 53",
          "latitude": "37.523659",
          "hardness": "126.903814",
          "longitude": "126.903814",
          "institutionNm": "영등포구청",
          "cmptncPolcsttnNm": "영등포경찰서",
          "cctvYn": "Y",
          "cctvNumber": "1",
          "prtcareaRw": "6~9",
          "referenceDate": "2019-05-03",
          "insttCode": "3180000",
          "insttNm": "서울특별시 영등포구"
        }, //영등포구
        {
          "fcltyKnd": "초등학교",
          "trgetFcltyNm": "종암초교",
          "rdnmadr": "서울특별시 동대문구 무학로44길 25",
          "lnmadr": "서울특별시 동대문구 제기동 1157",
          "latitude": "37.58230633",
          "hardness": "127.0318584",
          "longitude": "127.0318584",
          "institutionNm": "서울특별시 동대문구청",
          "cmptncPolcsttnNm": "동대문경찰서",
          "cctvYn": "Y",
          "cctvNumber": "3",
          "prtcareaRw": "null",
          "referenceDate": "2019-11-25",
          "insttCode": "3050000",
          "insttNm": "서울특별시 동대문구"
        },
        {
          "fcltyKnd": "초등학교",
          "trgetFcltyNm": "청량초교",
          "rdnmadr": "서울특별시 동대문구 회기로25길 31",
          "lnmadr": "서울특별시 동대문구 회기동 1-1",
          "latitude": "37.59230922",
          "hardness": "127.055908",
          "longitude": "127.055908",
          "institutionNm": "서울특별시 동대문구청",
          "cmptncPolcsttnNm": "동대문경찰서",
          "cctvYn": "Y",
          "cctvNumber": "3",
          "prtcareaRw": "null",
          "referenceDate": "2019-11-25",
          "insttCode": "3050000",
          "insttNm": "서울특별시 동대문구"
        },
        {
          "fcltyKnd": "초등학교",
          "trgetFcltyNm": "홍릉초교",
          "rdnmadr": "서울특별시 동대문구 회기로 90",
          "lnmadr": "서울특별시 동대문구 청량리동 206-44",
          "latitude": "37.59068743",
          "hardness": "127.0477047",
          "longitude": "127.0477047",
          "institutionNm": "서울특별시 동대문구청",
          "cmptncPolcsttnNm": "동대문경찰서",
          "cctvYn": "Y",
          "cctvNumber": "1",
          "prtcareaRw": "null",
          "referenceDate": "2019-11-25",
          "insttCode": "3050000",
          "insttNm": "서울특별시 동대문구"
        },
        {
          "fcltyKnd": "초등학교",
          "trgetFcltyNm": "배봉초교",
          "rdnmadr": "서울특별시 동대문구 사가정로 193",
          "lnmadr": "서울특별시 동대문구 전농동 3-111",
          "latitude": "37.58008059",
          "hardness": "127.0668713",
          "longitude": "127.0668713",
          "institutionNm": "서울특별시 동대문구청",
          "cmptncPolcsttnNm": "동대문경찰서",
          "cctvYn": "Y",
          "cctvNumber": "2",
          "prtcareaRw": "null",
          "referenceDate": "2019-11-25",
          "insttCode": "3050000",
          "insttNm": "서울특별시 동대문구"
        },
        {
          "fcltyKnd": "초등학교",
          "trgetFcltyNm": "군자초교",
          "rdnmadr": "서울특별시 동대문구 한천로6길 21",
          "lnmadr": "서울특별시 동대문구 장안1동 239-2",
          "latitude": "37.56412385",
          "hardness": "127.0605231",
          "longitude": "127.0605231",
          "institutionNm": "서울특별시 동대문구청",
          "cmptncPolcsttnNm": "동대문경찰서",
          "cctvYn": "Y",
          "cctvNumber": "3",
          "prtcareaRw": "null",
          "referenceDate": "2019-11-25",
          "insttCode": "3050000",
          "insttNm": "서울특별시 동대문구"
        },
        {
          "fcltyKnd": "유치원",
          "trgetFcltyNm": "군자초교병설유치원",
          "rdnmadr": "서울특별시 동대문구 한천로6길 21",
          "lnmadr": "서울특별시 동대문구 장안1동 239-2",
          "latitude": "37.56412385",
          "hardness": "127.0605231",
          "longitude": "127.0605231",
          "institutionNm": "서울특별시 동대문구청",
          "cmptncPolcsttnNm": "동대문경찰서",
          "cctvYn": "Y",
          "cctvNumber": "0",
          "prtcareaRw": "null",
          "referenceDate": "2019-11-25",
          "insttCode": "3050000",
          "insttNm": "서울특별시 동대문구"
        },
        {
          "fcltyKnd": "초등학교",
          "trgetFcltyNm": "답십리초교",
          "rdnmadr": "서울특별시 동대문구 전농로3길 23",
          "lnmadr": "서울특별시 동대문구 답십리동 274",
          "latitude": "37.56880432",
          "hardness": "127.0554295",
          "longitude": "127.0554295",
          "institutionNm": "서울특별시 동대문구청",
          "cmptncPolcsttnNm": "동대문경찰서",
          "cctvYn": "Y",
          "cctvNumber": "5",
          "prtcareaRw": "null",
          "referenceDate": "2019-11-25",
          "insttCode": "3050000",
          "insttNm": "서울특별시 동대문구"
        },
        {
          "fcltyKnd": "유치원",
          "trgetFcltyNm": "답십리초교병설유치원",
          "rdnmadr": "서울특별시 동대문구 전농로3길 23",
          "lnmadr": "서울특별시 동대문구 답십리동 274",
          "latitude": "37.56880432",
          "hardness": "127.0554295",
          "longitude": "127.0554295",
          "institutionNm": "서울특별시 동대문구청",
          "cmptncPolcsttnNm": "동대문경찰서",
          "cctvYn": "Y",
          "cctvNumber": "0",
          "prtcareaRw": "null",
          "referenceDate": "2019-11-25",
          "insttCode": "3050000",
          "insttNm": "서울특별시 동대문구"
        },
        {
          "fcltyKnd": "초등학교",
          "trgetFcltyNm": "동답초교",
          "rdnmadr": "서울특별시 동대문구 답십리로60길 12",
          "lnmadr": "서울특별시 동대문구 답십리동 2-24",
          "latitude": "37.57150295",
          "hardness": "127.0640336",
          "longitude": "127.0640336",
          "institutionNm": "서울특별시 동대문구청",
          "cmptncPolcsttnNm": "동대문경찰서",
          "cctvYn": "Y",
          "cctvNumber": "2",
          "prtcareaRw": "null",
          "referenceDate": "2019-11-25",
          "insttCode": "3050000",
          "insttNm": "서울특별시 동대문구"
        },
        {
          "fcltyKnd": "초등학교",
          "trgetFcltyNm": "신답초교",
          "rdnmadr": "서울특별시 동대문구 천호대로 177",
          "lnmadr": "서울특별시 동대문구 답십리동 463-13",
          "latitude": "37.57270542",
          "hardness": "127.0429615",
          "longitude": "127.0429615",
          "institutionNm": "서울특별시 동대문구청",
          "cmptncPolcsttnNm": "동대문경찰서",
          "cctvYn": "Y",
          "cctvNumber": "3",
          "prtcareaRw": "null",
          "referenceDate": "2019-11-25",
          "insttCode": "3050000",
          "insttNm": "서울특별시 동대문구"
        }, //동대문구
        {
          "fcltyKnd": "초등학교",
          "trgetFcltyNm": "고은초등학교",
          "rdnmadr": "서울특별시 서대문구 모래내로 441",
          "lnmadr": "서울특별시 서대문구 홍제1동 320-3",
          "latitude": "37.585093",
          "hardness": "126.943084",
          "longitude": "126.943084",
          "institutionNm": "서울특별시 서대문구청",
          "cmptncPolcsttnNm": "서울특별시 서대문경찰서",
          "cctvYn": "Y",
          "cctvNumber": "1",
          "prtcareaRw": "8~13",
          "referenceDate": "2019-03-04",
          "insttCode": "3120000",
          "insttNm": "서울특별시 서대문구"
        },
        {
          "fcltyKnd": "초등학교",
          "trgetFcltyNm": "명지초등학교",
          "rdnmadr": "서울특별시 서대문구 명지2길 32-20",
          "lnmadr": "서울특별시 서대문구 홍은2동 산26-127",
          "latitude": "37.583552",
          "hardness": "126.928514",
          "longitude": "126.928514",
          "institutionNm": "서울특별시 서대문구청",
          "cmptncPolcsttnNm": "서울특별시 서대문경찰서",
          "cctvYn": "Y",
          "cctvNumber": "2",
          "prtcareaRw": "6~8",
          "referenceDate": "2019-03-04",
          "insttCode": "3120000",
          "insttNm": "서울특별시 서대문구"
        },
        {
          "fcltyKnd": "초등학교",
          "trgetFcltyNm": "북가좌초등학교",
          "rdnmadr": "서울특별시 서대문구 거북골로19길 20",
          "lnmadr": "서울특별시 서대문구 북가좌1동 186-108",
          "latitude": "37.577685",
          "hardness": "126.907464",
          "longitude": "126.907464",
          "institutionNm": "서울특별시 서대문구청",
          "cmptncPolcsttnNm": "서울특별시 서대문경찰서",
          "cctvYn": "Y",
          "cctvNumber": "2",
          "prtcareaRw": "5~16",
          "referenceDate": "2019-03-04",
          "insttCode": "3120000",
          "insttNm": "서울특별시 서대문구"
        },
        {
          "fcltyKnd": "초등학교",
          "trgetFcltyNm": "연가초등학교",
          "rdnmadr": "서울특별시 서대문구 증가로12가길 49-50",
          "lnmadr": "서울특별시 서대문구 남가좌2동 364-6",
          "latitude": "37.579748",
          "hardness": "126.918057",
          "longitude": "126.918057",
          "institutionNm": "서울특별시 서대문구청",
          "cmptncPolcsttnNm": "서울특별시 서대문경찰서",
          "cctvYn": "Y",
          "cctvNumber": "4",
          "prtcareaRw": "6~20",
          "referenceDate": "2019-03-04",
          "insttCode": "3120000",
          "insttNm": "서울특별시 서대문구"
        },
        {
          "fcltyKnd": "초등학교",
          "trgetFcltyNm": "이대부속초등학교",
          "rdnmadr": "서울특별시 서대문구 성산로 512-39",
          "lnmadr": "서울특별시 서대문구 대신동 20",
          "latitude": "37.560729",
          "hardness": "126.942557",
          "longitude": "126.942557",
          "institutionNm": "서울특별시 서대문구청",
          "cmptncPolcsttnNm": "서울특별시 서대문경찰서",
          "cctvYn": "Y",
          "cctvNumber": "2",
          "prtcareaRw": "5~8",
          "referenceDate": "2019-03-04",
          "insttCode": "3120000",
          "insttNm": "서울특별시 서대문구"
        },
        {
          "fcltyKnd": "초등학교",
          "trgetFcltyNm": "인왕초등학교",
          "rdnmadr": "서울특별시 서대문구 세무서길 33-9",
          "lnmadr": "서울특별시 서대문구 홍제3동 245-1",
          "latitude": "37.590337",
          "hardness": "126.945194",
          "longitude": "126.945194",
          "institutionNm": "서울특별시 서대문구청",
          "cmptncPolcsttnNm": "서울특별시 서대문경찰서",
          "cctvYn": "Y",
          "cctvNumber": "5",
          "prtcareaRw": "13~15",
          "referenceDate": "2019-03-04",
          "insttCode": "3120000",
          "insttNm": "서울특별시 서대문구"
        },
        {
          "fcltyKnd": "유치원",
          "trgetFcltyNm": "현대홍익유치원",
          "rdnmadr": "서울특별시 서대문구 모래내로 430",
          "lnmadr": "서울특별시 서대문구 홍제1동 456",
          "latitude": "37.584244",
          "hardness": "126.942932",
          "longitude": "126.942932",
          "institutionNm": "서울특별시 서대문구청",
          "cmptncPolcsttnNm": "서울특별시 서대문경찰서",
          "cctvYn": "Y",
          "cctvNumber": "1",
          "prtcareaRw": "13~15",
          "referenceDate": "2019-03-04",
          "insttCode": "3120000",
          "insttNm": "서울특별시 서대문구"
        },
        {
          "fcltyKnd": "초등학교",
          "trgetFcltyNm": "창서초등학교",
          "rdnmadr": "서울특별시 서대문구 연세로5나길 30-3",
          "lnmadr": "서울특별시 서대문구 창천동 53-38",
          "latitude": "37.557798",
          "hardness": "126.933906",
          "longitude": "126.933906",
          "institutionNm": "서울특별시 서대문구청",
          "cmptncPolcsttnNm": "서울특별시 서대문경찰서",
          "cctvYn": "Y",
          "cctvNumber": "5",
          "prtcareaRw": "3~8",
          "referenceDate": "2019-03-04",
          "insttCode": "3120000",
          "insttNm": "서울특별시 서대문구"
        },
        {
          "fcltyKnd": "초등학교",
          "trgetFcltyNm": "추계초등학교",
          "rdnmadr": "서울특별시 서대문구 북아현로11가길 7",
          "lnmadr": "서울특별시 서대문구 북아현동 190-1",
          "latitude": "37.563671",
          "hardness": "126.953412",
          "longitude": "126.953412",
          "institutionNm": "서울특별시 서대문구청",
          "cmptncPolcsttnNm": "서울특별시 서대문경찰서",
          "cctvYn": "Y",
          "cctvNumber": "2",
          "prtcareaRw": "4~14",
          "referenceDate": "2019-03-04",
          "insttCode": "3120000",
          "insttNm": "서울특별시 서대문구"
        },
        {
          "fcltyKnd": "초등학교",
          "trgetFcltyNm": "경기초등학교",
          "rdnmadr": "서울특별시 서대문구 경기대로9길 10",
          "lnmadr": "서울특별시 서대문구 충정로2가 70-2",
          "latitude": "37.565347",
          "hardness": "126.962782",
          "longitude": "126.962782",
          "institutionNm": "서울특별시 서대문구청",
          "cmptncPolcsttnNm": "서울특별시 서대문경찰서",
          "cctvYn": "Y",
          "cctvNumber": "5",
          "prtcareaRw": "11~13",
          "referenceDate": "2019-03-04",
          "insttCode": "3120000",
          "insttNm": "서울특별시 서대문구"
        }, //서대문구
        {
          "fcltyKnd": "외국인학교",
          "trgetFcltyNm": "한국켄트외국인학교",
          "rdnmadr": "서울특별시 광진구 자양로35길 13(구의동)",
          "lnmadr": "서울특별시 광진구 구의동 619-30",
          "latitude": "37.546694",
          "hardness": "127.085584",
          "longitude": "127.085584",
          "institutionNm": "서울특별시청",
          "cmptncPolcsttnNm": "광진경찰서",
          "cctvYn": "Y",
          "cctvNumber": "4",
          "prtcareaRw": "null",
          "referenceDate": "2019-02-20",
          "insttCode": "3040000",
          "insttNm": "서울특별시 광진구"
        },
        {
          "fcltyKnd": "어린이집",
          "trgetFcltyNm": "꿈동산몬테소리어린이집",
          "rdnmadr": "서울특별시 광진구 면목로4길 3 (군자동)",
          "lnmadr": "서울특별시 광진구 군자동 50",
          "latitude": "37.555785",
          "hardness": "127.067272",
          "longitude": "127.067272",
          "institutionNm": "서울특별시청",
          "cmptncPolcsttnNm": "광진경찰서",
          "cctvYn": "Y",
          "cctvNumber": "1",
          "prtcareaRw": "null",
          "referenceDate": "2019-02-20",
          "insttCode": "3040000",
          "insttNm": "서울특별시 광진구"
        },
        {
          "fcltyKnd": "어린이집",
          "trgetFcltyNm": "우리티움아이어린이집",
          "rdnmadr": "서울특별시 광진구 구의로4길 21 (구의동)",
          "lnmadr": "서울특별시 광진구 구의3동 209-44",
          "latitude": "37.540118",
          "hardness": "127.090531",
          "longitude": "127.090531",
          "institutionNm": "서울특별시청",
          "cmptncPolcsttnNm": "광진경찰서",
          "cctvYn": "Y",
          "cctvNumber": "1",
          "prtcareaRw": "null",
          "referenceDate": "2019-02-20",
          "insttCode": "3040000",
          "insttNm": "서울특별시 광진구"
        },
        {
          "fcltyKnd": "유치원",
          "trgetFcltyNm": "양진병설유치원",
          "rdnmadr": "서울특별시 광진구 광장동 워커힐길32",
          "lnmadr": "서울특별시 광진구 광장동 414-1",
          "latitude": "37.544266",
          "hardness": "127.096242",
          "longitude": "127.096242",
          "institutionNm": "서울특별시청",
          "cmptncPolcsttnNm": "광진경찰서",
          "cctvYn": "Y",
          "cctvNumber": "1",
          "prtcareaRw": "null",
          "referenceDate": "2019-02-20",
          "insttCode": "3040000",
          "insttNm": "서울특별시 광진구"
        },
        {
          "fcltyKnd": "유치원",
          "trgetFcltyNm": "양남병설유치원",
          "rdnmadr": "서울특별시 광진구 뚝섬로64길 71",
          "lnmadr": "서울특별시 광진구 자양2동 692",
          "latitude": "37.531018",
          "hardness": "127.087521",
          "longitude": "127.087521",
          "institutionNm": "서울특별시청",
          "cmptncPolcsttnNm": "광진경찰서",
          "cctvYn": "Y",
          "cctvNumber": "1",
          "prtcareaRw": "null",
          "referenceDate": "2019-02-20",
          "insttCode": "3040000",
          "insttNm": "서울특별시 광진구"
        },
        {
          "fcltyKnd": "유치원",
          "trgetFcltyNm": "신자병설유치원",
          "rdnmadr": "서울특별시 광진구 자양동 뚝섬로46길 64",
          "lnmadr": "서울특별시 광진구 자양2동 591",
          "latitude": "37.530017",
          "hardness": "127.073300",
          "longitude": "127.073300",
          "institutionNm": "서울특별시청",
          "cmptncPolcsttnNm": "광진경찰서",
          "cctvYn": "Y",
          "cctvNumber": "1",
          "prtcareaRw": "null",
          "referenceDate": "2019-02-20",
          "insttCode": "3040000",
          "insttNm": "서울특별시 광진구"
        },
        {
          "fcltyKnd": "유치원",
          "trgetFcltyNm": "구의병설유치원",
          "rdnmadr": "서울특별시 광진구 광나루로30길 49",
          "lnmadr": "서울특별시 광진구 화양동 303-9",
          "latitude": "37.542822",
          "hardness": "127.077355",
          "longitude": "127.077355",
          "institutionNm": "서울특별시청",
          "cmptncPolcsttnNm": "광진경찰서",
          "cctvYn": "Y",
          "cctvNumber": "1",
          "prtcareaRw": "null",
          "referenceDate": "2019-02-20",
          "insttCode": "3040000",
          "insttNm": "서울특별시 광진구"
        },
        {
          "fcltyKnd": "유치원",
          "trgetFcltyNm": "아이조아유치원",
          "rdnmadr": "서울특별시 광진구 긴고랑로 7길 65",
          "lnmadr": "서울특별시 광진구 중곡3동 191-79",
          "latitude": "37.566152",
          "hardness": "127.078271",
          "longitude": "127.078271",
          "institutionNm": "서울특별시청",
          "cmptncPolcsttnNm": "광진경찰서",
          "cctvYn": "Y",
          "cctvNumber": "1",
          "prtcareaRw": "null",
          "referenceDate": "2019-02-20",
          "insttCode": "3040000",
          "insttNm": "서울특별시 광진구"
        },
        {
          "fcltyKnd": "유치원",
          "trgetFcltyNm": "자양유치원",
          "rdnmadr": "서울특별시 광진구 자양로5길 36",
          "lnmadr": "서울특별시 광진구 자양2동 662-5",
          "latitude": "37.531156",
          "hardness": "127.081549",
          "longitude": "127.081549",
          "institutionNm": "서울특별시청",
          "cmptncPolcsttnNm": "광진경찰서",
          "cctvYn": "Y",
          "cctvNumber": "1",
          "prtcareaRw": "null",
          "referenceDate": "2019-02-20",
          "insttCode": "3040000",
          "insttNm": "서울특별시 광진구"
        },
        {
          "fcltyKnd": "유치원",
          "trgetFcltyNm": "광장유치원",
          "rdnmadr": "서울특별시 광진구 광장로7길 17 (광장동)",
          "lnmadr": "서울특별시 광진구 광장동 272-2",
          "latitude": "37.548432",
          "hardness": "127.102936",
          "longitude": "127.102936",
          "institutionNm": "서울특별시청",
          "cmptncPolcsttnNm": "광진경찰서",
          "cctvYn": "Y",
          "cctvNumber": "2",
          "prtcareaRw": "null",
          "referenceDate": "2019-02-20",
          "insttCode": "3040000",
          "insttNm": "서울특별시 광진구"
        }, //광진구
        {
          "fcltyKnd": "초등학교",
          "trgetFcltyNm": "삼성초등학교",
          "rdnmadr": "서울특별시 관악구 대학7길 52",
          "lnmadr": "서울특별시 관악구 대학동 233-1",
          "latitude": "37.4678163",
          "hardness": "126.940952",
          "longitude": "126.940952",
          "institutionNm": "서울특별시 관악구청",
          "cmptncPolcsttnNm": "서울관악경찰서",
          "cctvYn": "Y",
          "cctvNumber": "2",
          "prtcareaRw": "6~8",
          "referenceDate": "2019-04-30",
          "insttCode": "3200000",
          "insttNm": "서울특별시 관악구"
        },
        {
          "fcltyKnd": "초등학교",
          "trgetFcltyNm": "신림초등학교",
          "rdnmadr": "서울특별시 관악구 문성로28길 31",
          "lnmadr": "서울특별시 관악구 신원동 418-1",
          "latitude": "37.4771503",
          "hardness": "126.9272999",
          "longitude": "126.9272999",
          "institutionNm": "서울특별시 관악구청",
          "cmptncPolcsttnNm": "서울관악경찰서",
          "cctvYn": "Y",
          "cctvNumber": "7",
          "prtcareaRw": "6~20",
          "referenceDate": "2019-04-30",
          "insttCode": "3200000",
          "insttNm": "서울특별시 관악구"
        },
        {
          "fcltyKnd": "초등학교",
          "trgetFcltyNm": "신봉초등학교",
          "rdnmadr": "서울특별시 관악구 양녕로6나길 1",
          "lnmadr": "서울특별시 관악구 중앙동 458",
          "latitude": "37.4854747",
          "hardness": "126.9492175",
          "longitude": "126.9492175",
          "institutionNm": "서울특별시 관악구청",
          "cmptncPolcsttnNm": "서울관악경찰서",
          "cctvYn": "Y",
          "cctvNumber": "10",
          "prtcareaRw": "5~8",
          "referenceDate": "2019-04-30",
          "insttCode": "3200000",
          "insttNm": "서울특별시 관악구"
        },
        {
          "fcltyKnd": "초등학교",
          "trgetFcltyNm": "은천초등학교",
          "rdnmadr": "서울특별시 관악구 은천로 69",
          "lnmadr": "서울특별시 관악구 은천동 622-1",
          "latitude": "37.4868591",
          "hardness": "126.9429033",
          "longitude": "126.9429033",
          "institutionNm": "서울특별시 관악구청",
          "cmptncPolcsttnNm": "서울관악경찰서",
          "cctvYn": "Y",
          "cctvNumber": "5",
          "prtcareaRw": "6~20",
          "referenceDate": "2019-04-30",
          "insttCode": "3200000",
          "insttNm": "서울특별시 관악구"
        },
        {
          "fcltyKnd": "초등학교",
          "trgetFcltyNm": "봉천초등학교",
          "rdnmadr": "서울특별시 관악구 행운1라길 17",
          "lnmadr": "서울특별시 관악구 행운동 28-85",
          "latitude": "37.4829254",
          "hardness": "126.9578363",
          "longitude": "126.9578363",
          "institutionNm": "서울특별시 관악구청",
          "cmptncPolcsttnNm": "서울관악경찰서",
          "cctvYn": "Y",
          "cctvNumber": "5",
          "prtcareaRw": "6~12",
          "referenceDate": "2019-04-30",
          "insttCode": "3200000",
          "insttNm": "서울특별시 관악구"
        },
        {
          "fcltyKnd": "초등학교",
          "trgetFcltyNm": "신성초등학교",
          "rdnmadr": "서울특별시 관악구 신림로 114",
          "lnmadr": "서울특별시 관악구 서림동 117",
          "latitude": "37.4717141",
          "hardness": "126.9371520",
          "longitude": "126.9371520",
          "institutionNm": "서울특별시 관악구청",
          "cmptncPolcsttnNm": "서울관악경찰서",
          "cctvYn": "Y",
          "cctvNumber": "3",
          "prtcareaRw": "6~15",
          "referenceDate": "2019-04-30",
          "insttCode": "3200000",
          "insttNm": "서울특별시 관악구"
        },
        {
          "fcltyKnd": "초등학교",
          "trgetFcltyNm": "봉현초등학교",
          "rdnmadr": "서울특별시 관악구 성현로 117",
          "lnmadr": "서울특별시 관악구 성현동 1704",
          "latitude": "37.4910197",
          "hardness": "126.9556171",
          "longitude": "126.9556171",
          "institutionNm": "서울특별시 관악구청",
          "cmptncPolcsttnNm": "서울관악경찰서",
          "cctvYn": "Y",
          "cctvNumber": "4",
          "prtcareaRw": "6~20",
          "referenceDate": "2019-04-30",
          "insttCode": "3200000",
          "insttNm": "서울특별시 관악구"
        },
        {
          "fcltyKnd": "초등학교",
          "trgetFcltyNm": "원신초등학교",
          "rdnmadr": "서울특별시 관악구 광신길 177",
          "lnmadr": "서울특별시 관악구 삼성동 336",
          "latitude": "37.4670480",
          "hardness": "126.9274239",
          "longitude": "126.9274239",
          "institutionNm": "서울특별시 관악구청",
          "cmptncPolcsttnNm": "서울관악경찰서",
          "cctvYn": "Y",
          "cctvNumber": "3",
          "prtcareaRw": "4~12",
          "referenceDate": "2019-04-30",
          "insttCode": "3200000",
          "insttNm": "서울특별시 관악구"
        },
        {
          "fcltyKnd": "초등학교",
          "trgetFcltyNm": "조원초등학교",
          "rdnmadr": "서울특별시 관악구 조원로 67",
          "lnmadr": "서울특별시 관악구 조원동 548",
          "latitude": "37.484114",
          "hardness": "126.9094507",
          "longitude": "126.9094507",
          "institutionNm": "서울특별시 관악구청",
          "cmptncPolcsttnNm": "서울관악경찰서",
          "cctvYn": "Y",
          "cctvNumber": "4",
          "prtcareaRw": "6~20",
          "referenceDate": "2019-04-30",
          "insttCode": "3200000",
          "insttNm": "서울특별시 관악구"
        },
        {
          "fcltyKnd": "유치원",
          "trgetFcltyNm": "건영유치원",
          "rdnmadr": "서울특별시 관악구 조원로 114",
          "lnmadr": "서울특별시 관악구 신사동 513-17",
          "latitude": "37.484844",
          "hardness": "126.914908",
          "longitude": "126.914908",
          "institutionNm": "서울특별시 관악구청",
          "cmptncPolcsttnNm": "서울관악경찰서",
          "cctvYn": "Y",
          "cctvNumber": "3",
          "prtcareaRw": "6~12",
          "referenceDate": "2019-04-30",
          "insttCode": "3200000",
          "insttNm": "서울특별시 관악구"
        }, //관악구
        {
          "fcltyKnd": "유치원",
          "trgetFcltyNm": "새보람유치원",
          "rdnmadr": "서울특별시 은평구 불광로 107",
          "lnmadr": "서울특별시 은평구 불광로 107",
          "latitude": "37.6162634000",
          "hardness": "126.9326390000",
          "longitude": "126.9326390000",
          "institutionNm": "서울특별시 은평구",
          "cmptncPolcsttnNm": "은평경찰서",
          "cctvYn": "Y",
          "cctvNumber": "1",
          "prtcareaRw": "15",
          "referenceDate": "2019-07-31",
          "insttCode": "3110000",
          "insttNm": "서울특별시 은평구"
        },
        {
          "fcltyKnd": "유치원",
          "trgetFcltyNm": "라라유치원",
          "rdnmadr": "서울특별시 은평구 갈현로 170-1",
          "lnmadr": "서울특별시 은평구 갈현로 170-1",
          "latitude": "37.6131390000",
          "hardness": "126.9119458",
          "longitude": "126.9119458",
          "institutionNm": "서울특별시 은평구",
          "cmptncPolcsttnNm": "은평경찰서",
          "cctvYn": "Y",
          "cctvNumber": "1",
          "prtcareaRw": "6",
          "referenceDate": "2019-07-31",
          "insttCode": "3110000",
          "insttNm": "서울특별시 은평구"
        },
        {
          "fcltyKnd": "유치원",
          "trgetFcltyNm": "무지개나라유치원",
          "rdnmadr": "서울특별시 은평구 가좌로7다길 13",
          "lnmadr": "서울특별시 은평구 가좌로7다길 13",
          "latitude": "37.5845870000",
          "hardness": "126.9180933",
          "longitude": "126.9180933",
          "institutionNm": "서울특별시 은평구",
          "cmptncPolcsttnNm": "서부경찰서",
          "cctvYn": "Y",
          "cctvNumber": "1",
          "prtcareaRw": "6",
          "referenceDate": "2019-07-31",
          "insttCode": "3110000",
          "insttNm": "서울특별시 은평구"
        },
        {
          "fcltyKnd": "유치원",
          "trgetFcltyNm": "색동유치원",
          "rdnmadr": "서울특별시 은평구 갈현로 212-1",
          "lnmadr": "서울특별시 은평구 갈현로 212-1",
          "latitude": "37.6160550000",
          "hardness": "126.9142240000",
          "longitude": "126.9142240000",
          "institutionNm": "서울특별시 은평구",
          "cmptncPolcsttnNm": "은평경찰서",
          "cctvYn": "Y",
          "cctvNumber": "1",
          "prtcareaRw": "15",
          "referenceDate": "2019-07-31",
          "insttCode": "3110000",
          "insttNm": "서울특별시 은평구"
        },
        {
          "fcltyKnd": "유치원",
          "trgetFcltyNm": "동북유치원",
          "rdnmadr": "서울특별시 은평구 진관4로 31",
          "lnmadr": "서울특별시 은평구 진관4로 31",
          "latitude": "37.6443251537",
          "hardness": "126.9248133058",
          "longitude": "126.9248133058",
          "institutionNm": "서울특별시 은평구",
          "cmptncPolcsttnNm": "은평경찰서",
          "cctvYn": "Y",
          "cctvNumber": "1",
          "prtcareaRw": "10",
          "referenceDate": "2019-07-31",
          "insttCode": "3110000",
          "insttNm": "서울특별시 은평구"
        },
        {
          "fcltyKnd": "유치원",
          "trgetFcltyNm": "동산유치원",
          "rdnmadr": "서울특별시 은평구 증산서길 88",
          "lnmadr": "서울특별시 은평구 증산서길 88",
          "latitude": "37.5839762",
          "hardness": "126.9072260000",
          "longitude": "126.9072260000",
          "institutionNm": "서울특별시 은평구",
          "cmptncPolcsttnNm": "서부경찰서",
          "cctvYn": "Y",
          "cctvNumber": "1",
          "prtcareaRw": "10",
          "referenceDate": "2019-07-31",
          "insttCode": "3110000",
          "insttNm": "서울특별시 은평구"
        },
        {
          "fcltyKnd": "유치원",
          "trgetFcltyNm": "유정유치원",
          "rdnmadr": "서울특별시 은평구 진흥로12길 23",
          "lnmadr": "서울특별시 은평구 진흥로12길 23",
          "latitude": "37.6066376000",
          "hardness": "126.9267230000",
          "longitude": "126.9267230000",
          "institutionNm": "서울특별시 은평구",
          "cmptncPolcsttnNm": "서부경찰서",
          "cctvYn": "Y",
          "cctvNumber": "1",
          "prtcareaRw": "6",
          "referenceDate": "2019-07-31",
          "insttCode": "3110000",
          "insttNm": "서울특별시 은평구"
        },
        {
          "fcltyKnd": "유치원",
          "trgetFcltyNm": "다우림유치원",
          "rdnmadr": "서울특별시 은평구 증산로21길 22",
          "lnmadr": "서울특별시 은평구 증산로21길 22",
          "latitude": "37.5961970000",
          "hardness": "126.9123080000",
          "longitude": "126.9123080000",
          "institutionNm": "서울특별시 은평구",
          "cmptncPolcsttnNm": "서부경찰서",
          "cctvYn": "Y",
          "cctvNumber": "1",
          "prtcareaRw": "6",
          "referenceDate": "2019-07-31",
          "insttCode": "3110000",
          "insttNm": "서울특별시 은평구"
        },
        {
          "fcltyKnd": "유치원",
          "trgetFcltyNm": "진관유치원",
          "rdnmadr": "서울특별시 은평구 진관2로 111-16",
          "lnmadr": "서울특별시 은평구 진관2로 111-16",
          "latitude": "37.6347136025",
          "hardness": "126.9309589643",
          "longitude": "126.9309589643",
          "institutionNm": "서울특별시 은평구",
          "cmptncPolcsttnNm": "은평경찰서",
          "cctvYn": "Y",
          "cctvNumber": "1",
          "prtcareaRw": "12",
          "referenceDate": "2019-07-31",
          "insttCode": "3110000",
          "insttNm": "서울특별시 은평구"
        },
        {
          "fcltyKnd": "초등학교",
          "trgetFcltyNm": "응암초등",
          "rdnmadr": "서울특별시 은평구 가좌로6길 20",
          "lnmadr": "서울특별시 은평구 가좌로6길 20",
          "latitude": "37.5882810000",
          "hardness": "126.9217624",
          "longitude": "126.9217624",
          "institutionNm": "서울특별시 은평구",
          "cmptncPolcsttnNm": "서부경찰서",
          "cctvYn": "Y",
          "cctvNumber": "10",
          "prtcareaRw": "4",
          "referenceDate": "2019-07-31",
          "insttCode": "3110000",
          "insttNm": "서울특별시 은평구"
        }, //은평구
        {
          "fcltyKnd": "유치원",
          "trgetFcltyNm": "하나유치원",
          "rdnmadr": "서울특별시 서초구 잠원로8길 13",
          "lnmadr": "서울특별시 서초구 잠원동 56-3",
          "latitude": "37.5152074",
          "hardness": "127.0102178",
          "longitude": "127.0102178",
          "institutionNm": "서울시 서초구",
          "cmptncPolcsttnNm": "서초경찰서",
          "cctvYn": "Y",
          "cctvNumber": "1",
          "prtcareaRw": "1",
          "referenceDate": "2019-06-03",
          "insttCode": "3210000",
          "insttNm": "서울특별시 서초구"
        },
        {
          "fcltyKnd": "유치원",
          "trgetFcltyNm": "석문유치원",
          "rdnmadr": "서울특별시 서초구 서초대로64길 73",
          "lnmadr": "서울특별시 서초구 서초1동 1634-1",
          "latitude": "37.4925169",
          "hardness": "127.0218007",
          "longitude": "127.0218007",
          "institutionNm": "서울시 서초구",
          "cmptncPolcsttnNm": "서초경찰서",
          "cctvYn": "Y",
          "cctvNumber": "1",
          "prtcareaRw": "2",
          "referenceDate": "2019-06-03",
          "insttCode": "3210000",
          "insttNm": "서울특별시 서초구"
        },
        {
          "fcltyKnd": "유치원",
          "trgetFcltyNm": "신반포중앙유치원",
          "rdnmadr": "서울특별시 서초구 나루터로4길 28",
          "lnmadr": "서울특별시 서초구 잠원동 60-3",
          "latitude": "37.5113149",
          "hardness": "127.012021",
          "longitude": "127.012021",
          "institutionNm": "서울시 서초구",
          "cmptncPolcsttnNm": "서초경찰서",
          "cctvYn": "Y",
          "cctvNumber": "1",
          "prtcareaRw": "1",
          "referenceDate": "2019-06-03",
          "insttCode": "3210000",
          "insttNm": "서울특별시 서초구"
        },
        {
          "fcltyKnd": "유치원",
          "trgetFcltyNm": "반포성모유치원",
          "rdnmadr": "서울특별시 서초구 신반포로15길 18",
          "lnmadr": "서울특별시 서초구 반포2동 4-1",
          "latitude": "37.5048482",
          "hardness": "126.9944697",
          "longitude": "126.9944697",
          "institutionNm": "서울시 서초구",
          "cmptncPolcsttnNm": "방배경찰서",
          "cctvYn": "Y",
          "cctvNumber": "1",
          "prtcareaRw": "1",
          "referenceDate": "2019-06-03",
          "insttCode": "3210000",
          "insttNm": "서울특별시 서초구"
        },
        {
          "fcltyKnd": "유치원",
          "trgetFcltyNm": "영생유치원",
          "rdnmadr": "서울특별시 서초구 신반포로19길 30",
          "lnmadr": "서울특별시 서초구 반포2동 4-10",
          "latitude": "37.5049871",
          "hardness": "126.995664",
          "longitude": "126.995664",
          "institutionNm": "서울시 서초구",
          "cmptncPolcsttnNm": "방배경찰서",
          "cctvYn": "Y",
          "cctvNumber": "1",
          "prtcareaRw": "1",
          "referenceDate": "2019-06-03",
          "insttCode": "3210000",
          "insttNm": "서울특별시 서초구"
        },
        {
          "fcltyKnd": "유치원",
          "trgetFcltyNm": "새성민유치원",
          "rdnmadr": "서울특별시 서초구 효령로 110",
          "lnmadr": "서울특별시 서초구 방배3동 981-2",
          "latitude": "37.4806567",
          "hardness": "126.9961191",
          "longitude": "126.9961191",
          "institutionNm": "서울시 서초구",
          "cmptncPolcsttnNm": "방배경찰서",
          "cctvYn": "Y",
          "cctvNumber": "1",
          "prtcareaRw": "1",
          "referenceDate": "2019-06-03",
          "insttCode": "3210000",
          "insttNm": "서울특별시 서초구"
        },
        {
          "fcltyKnd": "유치원",
          "trgetFcltyNm": "새순유치원",
          "rdnmadr": "서울특별시 서초구 서초대로15길 57",
          "lnmadr": "서울특별시 서초구 방배4동 831-12",
          "latitude": "37.4889507",
          "hardness": "126.9884182",
          "longitude": "126.9884182",
          "institutionNm": "서울시 서초구",
          "cmptncPolcsttnNm": "방배경찰서",
          "cctvYn": "Y",
          "cctvNumber": "1",
          "prtcareaRw": "1",
          "referenceDate": "2019-06-03",
          "insttCode": "3210000",
          "insttNm": "서울특별시 서초구"
        },
        {
          "fcltyKnd": "유치원",
          "trgetFcltyNm": "여나유치원",
          "rdnmadr": "서울특별시 서초구 서초중앙로 200",
          "lnmadr": "서울특별시 서초구 서초4동 1685",
          "latitude": "37.4985336",
          "hardness": "127.0155431",
          "longitude": "127.0155431",
          "institutionNm": "서울시 서초구",
          "cmptncPolcsttnNm": "서초경찰서",
          "cctvYn": "Y",
          "cctvNumber": "1",
          "prtcareaRw": "1",
          "referenceDate": "2019-06-03",
          "insttCode": "3210000",
          "insttNm": "서울특별시 서초구"
        },
        {
          "fcltyKnd": "유치원",
          "trgetFcltyNm": "양재천사유치원",
          "rdnmadr": "서울특별시 서초구 바우뫼로 89",
          "lnmadr": "서울특별시 서초구 양재1동 154-2",
          "latitude": "37.47435569",
          "hardness": "127.0311795",
          "longitude": "127.0311795",
          "institutionNm": "서울시 서초구",
          "cmptncPolcsttnNm": "서초경찰서",
          "cctvYn": "Y",
          "cctvNumber": "1",
          "prtcareaRw": "1",
          "referenceDate": "2019-06-03",
          "insttCode": "3210000",
          "insttNm": "서울특별시 서초구"
        },
        {
          "fcltyKnd": "유치원",
          "trgetFcltyNm": "반포병설유치원",
          "rdnmadr": "서울특별시 서초구 신반포로 55-4",
          "lnmadr": "서울특별시 서초구 반포본동 937",
          "latitude": "37.5027416",
          "hardness": "126.9910992",
          "longitude": "126.9910992",
          "institutionNm": "서울시 서초구",
          "cmptncPolcsttnNm": "방배경찰서",
          "cctvYn": "Y",
          "cctvNumber": "1",
          "prtcareaRw": "1",
          "referenceDate": "2019-06-03",
          "insttCode": "3210000",
          "insttNm": "서울특별시 서초구"
        }, //서초구
        {
          "fcltyKnd": "어린이집",
          "trgetFcltyNm": "아동회관어린이집",
          "rdnmadr": "서울특별시 종로구 지봉로13길 14",
          "lnmadr": "서울특별시 종로구 창신동 산6-25",
          "latitude": "37.5788167",
          "hardness": "127.0146310",
          "longitude": "127.0146310",
          "institutionNm": "종로구청",
          "cmptncPolcsttnNm": "혜화경찰서",
          "cctvYn": "Y",
          "cctvNumber": "1",
          "prtcareaRw": "6~15",
          "referenceDate": "2019-01-14",
          "insttCode": "3000000",
          "insttNm": "서울특별시 종로구"
        },
        {
          "fcltyKnd": "특수학교",
          "trgetFcltyNm": "수도사랑의학교",
          "rdnmadr": "서울특별시 종로구 사직로7길17",
          "lnmadr": "서울특별시 종로구 사직동 262-57",
          "latitude": "37.5747210",
          "hardness": "126.9652170",
          "longitude": "126.9652170",
          "institutionNm": "종로구청",
          "cmptncPolcsttnNm": "종로경찰서",
          "cctvYn": "Y",
          "cctvNumber": "1",
          "prtcareaRw": "12",
          "referenceDate": "2019-01-14",
          "insttCode": "3000000",
          "insttNm": "서울특별시 종로구"
        },
        {
          "fcltyKnd": "유치원",
          "trgetFcltyNm": "세종유치원",
          "rdnmadr": "서울특별시 종로구 사직로8길 9",
          "lnmadr": "서울특별시 종로구 필운동 278-4",
          "latitude": "37.5754770",
          "hardness": "126.9699520",
          "longitude": "126.9699520",
          "institutionNm": "종로구청",
          "cmptncPolcsttnNm": "종로경찰서",
          "cctvYn": "Y",
          "cctvNumber": "1",
          "prtcareaRw": "25",
          "referenceDate": "2019-01-14",
          "insttCode": "3000000",
          "insttNm": "서울특별시 종로구"
        },
        {
          "fcltyKnd": "초등학교",
          "trgetFcltyNm": "세검정초등학교",
          "rdnmadr": "서울특별시 종로구 세검정로9길1",
          "lnmadr": "서울특별시 종로구 신영동 219-4",
          "latitude": "37.6033878",
          "hardness": "126.9608999",
          "longitude": "126.9608999",
          "institutionNm": "종로구청",
          "cmptncPolcsttnNm": "종로경찰서",
          "cctvYn": "Y",
          "cctvNumber": "3",
          "prtcareaRw": "4~8",
          "referenceDate": "2019-01-14",
          "insttCode": "3000000",
          "insttNm": "서울특별시 종로구"
        },
        {
          "fcltyKnd": "유치원",
          "trgetFcltyNm": "세검정유치원",
          "rdnmadr": "서울특별시 종로구 자하문로310",
          "lnmadr": "서울특별시 종로구 홍지동 94-9",
          "latitude": "37.6001344",
          "hardness": "126.9594842",
          "longitude": "126.9594842",
          "institutionNm": "종로구청",
          "cmptncPolcsttnNm": "종로경찰서",
          "cctvYn": "Y",
          "cctvNumber": "1",
          "prtcareaRw": "35",
          "referenceDate": "2019-01-14",
          "insttCode": "3000000",
          "insttNm": "서울특별시 종로구"
        },
        {
          "fcltyKnd": "어린이집",
          "trgetFcltyNm": "서울청사한빛어린이집",
          "rdnmadr": "서울특별시 종로구 효자로39",
          "lnmadr": "서울특별시 종로구 창성동 117-6",
          "latitude": "37.5797195",
          "hardness": "126.9732210",
          "longitude": "126.9732210",
          "institutionNm": "종로구청",
          "cmptncPolcsttnNm": "종로경찰서",
          "cctvYn": "Y",
          "cctvNumber": "1",
          "prtcareaRw": "12",
          "referenceDate": "2019-01-14",
          "insttCode": "3000000",
          "insttNm": "서울특별시 종로구"
        },
        {
          "fcltyKnd": "초등학교",
          "trgetFcltyNm": "서울사대부설초등학교",
          "rdnmadr": "서울특별시 종로구 대학로64",
          "lnmadr": "서울특별시 종로구 이화동 149",
          "latitude": "37.5770930",
          "hardness": "127.0038022",
          "longitude": "127.0038022",
          "institutionNm": "종로구청",
          "cmptncPolcsttnNm": "혜화경찰서",
          "cctvYn": "Y",
          "cctvNumber": "3",
          "prtcareaRw": "6~10",
          "referenceDate": "2019-01-14",
          "insttCode": "3000000",
          "insttNm": "서울특별시 종로구"
        },
        {
          "fcltyKnd": "특수학교",
          "trgetFcltyNm": "서울맹,농학교",
          "rdnmadr": "서울특별시 종로구 필운대로 97, 필운대로103",
          "lnmadr": "서울특별시 종로구 종로구 신교동1-4, 신교동 1-1",
          "latitude": "37.5845561",
          "hardness": "126.9676572",
          "longitude": "126.9676572",
          "institutionNm": "종로구청",
          "cmptncPolcsttnNm": "종로경찰서",
          "cctvYn": "Y",
          "cctvNumber": "2",
          "prtcareaRw": "12",
          "referenceDate": "2019-01-14",
          "insttCode": "3000000",
          "insttNm": "서울특별시 종로구"
        },
        {
          "fcltyKnd": "초등학교",
          "trgetFcltyNm": "효제초등학교",
          "rdnmadr": "서울특별시 종로구 대학로12",
          "lnmadr": "서울특별시 종로구 효제동 255-4",
          "latitude": "37.5728828",
          "hardness": "127.0032570",
          "longitude": "127.0032570",
          "institutionNm": "종로구청",
          "cmptncPolcsttnNm": "혜화경찰서",
          "cctvYn": "Y",
          "cctvNumber": "4",
          "prtcareaRw": "20~25",
          "referenceDate": "2019-01-14",
          "insttCode": "3000000",
          "insttNm": "서울특별시 종로구"
        },
        {
          "fcltyKnd": "초등학교",
          "trgetFcltyNm": "혜화초등학교",
          "rdnmadr": "서울특별시 종로구 혜화로 32",
          "lnmadr": "서울특별시 종로구 명륜동1가 1-27",
          "latitude": "37.5888137",
          "hardness": "127.0000249",
          "longitude": "127.0000249",
          "institutionNm": "종로구청",
          "cmptncPolcsttnNm": "혜화경찰서",
          "cctvYn": "Y",
          "cctvNumber": "2",
          "prtcareaRw": "15",
          "referenceDate": "2019-01-14",
          "insttCode": "3000000",
          "insttNm": "서울특별시 종로구"
        } //종로구
      ], //item
      "totalCount": "76",
      "numOfRows": "10",
      "pageNo": "1"
    }
  }
}