/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.27
 * Generated at: 2020-05-18 05:52:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class HieEmpWrite_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/javax.servlet.jsp.jstl-1.2.1.jar", Long.valueOf(1589365354794L));
    _jspx_dependants.put("jar:file:/C:/Users/wlsgm/Desktop/1조%20학습기록%20저장소/조별과제/2차마지막조별과제(2차요구사항)/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Emp_Model2_Mvc_Team1/WEB-INF/lib/javax.servlet.jsp.jstl-1.2.1.jar!/META-INF/c.tld", Long.valueOf(1323225978000L));
    _jspx_dependants.put("jar:file:/C:/Users/wlsgm/Desktop/1조%20학습기록%20저장소/조별과제/2차마지막조별과제(2차요구사항)/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Emp_Model2_Mvc_Team1/WEB-INF/lib/javax.servlet.jsp.jstl-1.2.1.jar!/META-INF/fn.tld", Long.valueOf(1323225978000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<!--[if lt IE 7]>      <html class=\"no-js lt-ie9 lt-ie8 lt-ie7\" lang=\"\"> <![endif]-->\r\n");
      out.write("<!--[if IE 7]>         <html class=\"no-js lt-ie9 lt-ie8\" lang=\"\"> <![endif]-->\r\n");
      out.write("<!--[if IE 8]>         <html class=\"no-js lt-ie9\" lang=\"\"> <![endif]-->\r\n");
      out.write("<!--[if gt IE 8]><!-->\r\n");
      out.write("<html class=\"no-js\" lang=\"en\">\r\n");
      out.write("<!--<![endif]-->\r\n");
      out.write("                                                                                                                                                                             \r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<title>Sufee Admin - HTML5 Admin Template</title>\r\n");
      out.write("<meta name=\"description\" content=\"Sufee Admin - HTML5 Admin Template\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\r\n");
      out.write("<!-- dataTable start -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css\"> \r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"./custom/dataTable/css/jquery.dataTables.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"./custom/dataTable/css/responsive.dataTables.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"./custom/dataTable/css/main.css\">\r\n");
      out.write("<!-- dataTable end  -->\r\n");
      out.write("\r\n");
      out.write("<!-- 부트스트랩 start -->\r\n");
      out.write("<link rel=\"apple-touch-icon\" href=\"apple-icon.png\">\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"favicon.ico\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("   href=\"vendors/bootstrap/dist/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("   href=\"vendors/font-awesome/css/font-awesome.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("   href=\"vendors/themify-icons/css/themify-icons.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("   href=\"vendors/flag-icon-css/css/flag-icon.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"vendors/selectFX/css/cs-skin-elastic.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"vendors/jqvmap/dist/jqvmap.min.css\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://use.fontawesome.com/releases/v5.7.0/css/all.css\"\r\n");
      out.write("\tintegrity=\"sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ\"\r\n");
      out.write("\tcrossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/style.css\">\r\n");
      out.write("\r\n");
      out.write("<link\r\n");
      out.write("   href='https://fonts.googleapis.com/css?family=Open+Sans:400,600,700,800'\r\n");
      out.write("   rel='stylesheet' type='text/css'>\r\n");
      out.write("<!-- 부트스트랩 end  -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("tr>th {\r\n");
      out.write("   text-align: center;\r\n");
      out.write("}\r\n");
      out.write("body{\r\n");
      out.write("padding : 3px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#tbody{\r\n");
      out.write("background-color:white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#tbody tr{\r\n");
      out.write("onmouseover:backgroundColor=gray;\r\n");
      out.write("onmouseout:this.style.backgroundColor=white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("   <!-- Left Panel -->\r\n");
      out.write("  ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/common/LeftMenu.jsp", out, false);
      out.write(" \r\n");
      out.write("   <!-- /Left Panel -->\r\n");
      out.write("\r\n");
      out.write("   <!-- Right Panel -->\r\n");
      out.write("   <div id=\"right-panel\" class=\"right-panel\">\r\n");
      out.write("\r\n");
      out.write("      <!-- Header-->\r\n");
      out.write("       ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/common/TopMenu.jsp", out, false);
      out.write("\r\n");
      out.write("      <!-- /Header -->\r\n");
      out.write("\r\n");
      out.write("      <div class=\"breadcrumbs\">\r\n");
      out.write("         <div class=\"col-sm-4\">\r\n");
      out.write("            <div class=\"page-header float-left\">\r\n");
      out.write("               <div class=\"page-title\">\r\n");
      out.write("                  <h1>계층형 게시판 페이지 입니다.</h1>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("         </div>\r\n");
      out.write("         <div class=\"col-sm-8\">\r\n");
      out.write("            <div class=\"page-header float-right\">\r\n");
      out.write("               <div class=\"page-title\">\r\n");
      out.write("               \r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("         </div>\r\n");
      out.write("      </div> \r\n");
      out.write("\r\n");
      out.write("      <!-- <form name=\"list\"> -->\r\n");
      out.write("      ");
      out.write("\r\n");
      out.write("      <!--  </form> -->\r\n");
      out.write("     <div class=\"main-panel\">\r\n");
      out.write("         <div class=\"content-wrapper\">\r\n");
      out.write("            <div class=\"row \">\r\n");
      out.write("               <div class=\"col-12\">\r\n");
      out.write("               \r\n");
      out.write("               \r\n");
      out.write("               \r\n");
      out.write("       <article>\r\n");
      out.write("\t\t<div class=\"container\" role=\"main\">\r\n");
      out.write("\t\t\t<h2>board Form</h2>\r\n");
      out.write("\t\t\t<form name=\"form\" id=\"form\" role=\"form\" method=\"post\"\r\n");
      out.write("\t\t\t\taction=\"HieEmpWriteok.do\">\r\n");
      out.write("\t\t\t\t<div class=\"mb-3\">\r\n");
      out.write("\t\t\t\t\t<label for=\"title\">제목</label> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"form-control\" name=\"subject\" id=\"title\"\r\n");
      out.write("\t\t\t\t\t\tplaceholder=\"제목을 입력해 주세요\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"mb-3\">\r\n");
      out.write("\t\t\t\t\t<label for=\"reg_id\">작성자</label> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"form-control\" name=\"writer\" id=\"reg_id\"\r\n");
      out.write("\t\t\t\t\t\tplaceholder=\"작성자를 입력해 주세요\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"mb-3\">\r\n");
      out.write("\t\t\t\t\t<label for=\"reg_id\">이메일</label> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"form-control\" name=\"email\" id=\"reg_id\"\r\n");
      out.write("\t\t\t\t\t\tplaceholder=\"이메일을 입력해 주세요\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"mb-3\">\r\n");
      out.write("\t\t\t\t\t<label for=\"reg_id\">홈페이지</label> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"form-control\" name=\"homepage\" id=\"reg_id\"\r\n");
      out.write("\t\t\t\t\t\tplaceholder=\"홈페이지를 입력해 주세요\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- 썸머노트 반영 -->\r\n");
      out.write("\t\t\t\t<div class=\"mb-3\">\r\n");
      out.write("\t\t\t\t\t<label for=\"content\">내용</label>\r\n");
      out.write("\t\t\t\t\t<textarea class=\"form-control\" rows=\"5\" name=\"content\" id=\"content\"\r\n");
      out.write("\t\t\t\t\t\tplaceholder=\"내용을 입력해 주세요\"></textarea>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"mb-3\">\r\n");
      out.write("\t\t\t\t\t<label for=\"reg_id\">비밀번호</label> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"form-control\" name=\"pwd\" id=\"reg_id\"\r\n");
      out.write("\t\t\t\t\t\tplaceholder=\"비밀번호를 입력해 주세요\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"btn btn-sm btn-primary\" id=\"btnSave\">저장</button>\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"btn btn-sm btn-primary\" id=\"btnList\">목록</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t</article>\r\n");
      out.write("              \r\n");
      out.write("            </div>\r\n");
      out.write("         </div>\r\n");
      out.write("         </div>\r\n");
      out.write("      </div> \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("<!-- .content -->\r\n");
      out.write("<!-- /#right-panel -->\r\n");
      out.write("\r\n");
      out.write("<!-- Right Panel -->\r\n");
      out.write("\r\n");
      out.write("<!-- 기존 부트스트랩 start-->\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("<!-- 기존 부트스트랩 end-->\r\n");
      out.write("\r\n");
      out.write("<script src=\"assets/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"//cdn.ckeditor.com/4.14.0/standard/ckeditor.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("   (function($) {\r\n");
      out.write("      \"use strict\";\r\n");
      out.write("      \r\n");
      out.write("  \tCKEDITOR.replace('content', {\r\n");
      out.write("\t\twidth:'100%',\r\n");
      out.write("\t\theight:'350'\r\n");
      out.write("\t});\r\n");
      out.write("      \r\n");
      out.write("      $(document).on('click', '#btnSave', function(e) {\r\n");
      out.write("  \t\te.preventDefault();\r\n");
      out.write("  \t\t$(\"#form\").submit();\r\n");
      out.write("  \t});\r\n");
      out.write("  \t\r\n");
      out.write("  \t$(document)\r\n");
      out.write("  \t\t\t.on(\r\n");
      out.write("  \t\t\t\t\t'click',\r\n");
      out.write("  \t\t\t\t\t'#btnList',\r\n");
      out.write("  \t\t\t\t\tfunction(e) {\r\n");
      out.write("  \t\t\t\t\t\te.preventDefault();\r\n");
      out.write("  \t\t\t\t\t\tlocation.href = \"HieEmpTable.do\";\r\n");
      out.write("  \t\t\t\t\t});\r\n");
      out.write("   })(jQuery);\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
