// 20200422141756
// http://api.data.go.kr/openapi/child-prtc-zn-std?pageNo=1&numOfRows=104&type=json&insttNm=%EC%84%9C%EC%9A%B8%ED%8A%B9%EB%B3%84%EC%8B%9C%20%EA%B0%95%EB%82%A8%EA%B5%AC&ServiceKey=skXA159lQs%2FIrfBwdy5vEAZdR4E3Pfrjz%2BMhGc8Od%2FCV7ODFqkaAczjP9yzdfvDw1SEj0PxrvLdE9U9Gf2KYgw%3D%3D

var data = {
    "response": {
      "header": {
        "resultCode": "00",
        "resultMsg": "NORMAL_SERVICE",
        "type": "json"
      },
      "body": {
        "items": [
          {
            "fcltyKnd": "유치원",
            "trgetFcltyNm": "돌샘유치원",
            "rdnmadr": "서울특별시 강남구 개포로 516",
            "lnmadr": "null",
            "latitude": "37.4891403199",
            "hardness": "127.0708697840",
            "longitude": "127.0708697840",
            "institutionNm": "서울특별시 강남구청",
            "cmptncPolcsttnNm": "수서경찰서",
            "cctvYn": "Y",
            "cctvNumber": "1",
            "prtcareaRw": "12.6",
            "referenceDate": "2019-12-20",
            "insttCode": "3220000",
            "insttNm": "서울특별시 강남구"
          },
          {
            "fcltyKnd": "유치원",
            "trgetFcltyNm": "신양유치원",
            "rdnmadr": "서울특별시 강남구 선릉로10길 18-6",
            "lnmadr": "null",
            "latitude": "37.483431",
            "hardness": "127.061678",
            "longitude": "127.061678",
            "institutionNm": "서울특별시 강남구청",
            "cmptncPolcsttnNm": "수서경찰서",
            "cctvYn": "Y",
            "cctvNumber": "2",
            "prtcareaRw": "6",
            "referenceDate": "2019-12-20",
            "insttCode": "3220000",
            "insttNm": "서울특별시 강남구"
          },
          {
            "fcltyKnd": "유치원",
            "trgetFcltyNm": "이화유치원",
            "rdnmadr": "서울특별시 강남구 개포로109길 9",
            "lnmadr": "null",
            "latitude": "37.495751",
            "hardness": "127.075096",
            "longitude": "127.075096",
            "institutionNm": "서울특별시 강남구청",
            "cmptncPolcsttnNm": "수서경찰서",
            "cctvYn": "Y",
            "cctvNumber": "2",
            "prtcareaRw": "15",
            "referenceDate": "2019-12-20",
            "insttCode": "3220000",
            "insttNm": "서울특별시 강남구"
          },
          {
            "fcltyKnd": "유치원",
            "trgetFcltyNm": "영동제일유치원",
            "rdnmadr": "서울특별시 강남구 삼성로120길 28",
            "lnmadr": "null",
            "latitude": "37.517579",
            "hardness": "127.053437",
            "longitude": "127.053437",
            "institutionNm": "서울특별시 강남구청",
            "cmptncPolcsttnNm": "강남경찰서",
            "cctvYn": "Y",
            "cctvNumber": "2",
            "prtcareaRw": "5.8",
            "referenceDate": "2019-12-20",
            "insttCode": "3220000",
            "insttNm": "서울특별시 강남구"
          },
          {
            "fcltyKnd": "유치원",
            "trgetFcltyNm": "소망유치원",
            "rdnmadr": "서울특별시 강남구 광평로56길 11",
            "lnmadr": "null",
            "latitude": "37.4879790845",
            "hardness": "127.1056313773",
            "longitude": "127.1056313773",
            "institutionNm": "서울특별시 강남구청",
            "cmptncPolcsttnNm": "수서경찰서",
            "cctvYn": "Y",
            "cctvNumber": "1",
            "prtcareaRw": "11",
            "referenceDate": "2019-12-20",
            "insttCode": "3220000",
            "insttNm": "서울특별시 강남구"
          },
          {
            "fcltyKnd": "유치원",
            "trgetFcltyNm": "청운유치원",
            "rdnmadr": "서울특별시 강남구 언주로65길 5",
            "lnmadr": "null",
            "latitude": "37.4950489901",
            "hardness": "127.045531",
            "longitude": "127.045531",
            "institutionNm": "서울특별시 강남구청",
            "cmptncPolcsttnNm": "수서경찰서",
            "cctvYn": "Y",
            "cctvNumber": "1",
            "prtcareaRw": "11.5",
            "referenceDate": "2019-12-20",
            "insttCode": "3220000",
            "insttNm": "서울특별시 강남구"
          },
          {
            "fcltyKnd": "유치원",
            "trgetFcltyNm": "묘동유치원",
            "rdnmadr": "서울특별시 강남구 도곡로78길 8",
            "lnmadr": "null",
            "latitude": "37.4974073916",
            "hardness": "127.058723",
            "longitude": "127.058723",
            "institutionNm": "서울특별시 강남구청",
            "cmptncPolcsttnNm": "수서경찰서",
            "cctvYn": "Y",
            "cctvNumber": "5",
            "prtcareaRw": "5.5",
            "referenceDate": "2019-12-20",
            "insttCode": "3220000",
            "insttNm": "서울특별시 강남구"
          },
          {
            "fcltyKnd": "유치원",
            "trgetFcltyNm": "푸른유치원",
            "rdnmadr": "서울특별시 강남구 일원로14길 25",
            "lnmadr": "null",
            "latitude": "37.4847980900",
            "hardness": "127.0811004779",
            "longitude": "127.0811004779",
            "institutionNm": "서울특별시 강남구청",
            "cmptncPolcsttnNm": "수서경찰서",
            "cctvYn": "Y",
            "cctvNumber": "1",
            "prtcareaRw": "15.2",
            "referenceDate": "2019-12-20",
            "insttCode": "3220000",
            "insttNm": "서울특별시 강남구"
          },
          {
            "fcltyKnd": "유치원",
            "trgetFcltyNm": "성요셉유치원",
            "rdnmadr": "서울특별시 강남구 도산대로83길 27",
            "lnmadr": "null",
            "latitude": "37.5262731393",
            "hardness": "127.0482111685",
            "longitude": "127.0482111685",
            "institutionNm": "서울특별시 강남구청",
            "cmptncPolcsttnNm": "강남경찰서",
            "cctvYn": "Y",
            "cctvNumber": "2",
            "prtcareaRw": "5.9",
            "referenceDate": "2019-12-20",
            "insttCode": "3220000",
            "insttNm": "서울특별시 강남구"
          },
          {
            "fcltyKnd": "유치원",
            "trgetFcltyNm": "강남유치원",
            "rdnmadr": "서울특별시 강남구 선릉로129길 31",
            "lnmadr": "null",
            "latitude": "37.515448",
            "hardness": "127.039009",
            "longitude": "127.039009",
            "institutionNm": "서울특별시 강남구청",
            "cmptncPolcsttnNm": "강남경찰서",
            "cctvYn": "Y",
            "cctvNumber": "2",
            "prtcareaRw": "8.6",
            "referenceDate": "2019-12-20",
            "insttCode": "3220000",
            "insttNm": "서울특별시 강남구"
          },
          {
            "fcltyKnd": "유치원",
            "trgetFcltyNm": "아란유치원",
            "rdnmadr": "서울특별시 강남구 압구정로 201",
            "lnmadr": "null",
            "latitude": "37.5315339928",
            "hardness": "127.0292753857",
            "longitude": "127.0292753857",
            "institutionNm": "서울특별시 강남구청",
            "cmptncPolcsttnNm": "강남경찰서",
            "cctvYn": "Y",
            "cctvNumber": "1",
            "prtcareaRw": "6",
            "referenceDate": "2019-12-20",
            "insttCode": "3220000",
            "insttNm": "서울특별시 강남구"
          },
          {
            "fcltyKnd": "유치원",
            "trgetFcltyNm": "은곡유치원",
            "rdnmadr": "서울특별시 강남구 헌릉로569길 41",
            "lnmadr": "null",
            "latitude": "37.4668200316",
            "hardness": "127.096934",
            "longitude": "127.096934",
            "institutionNm": "서울특별시 강남구청",
            "cmptncPolcsttnNm": "수서경찰서",
            "cctvYn": "Y",
            "cctvNumber": "1",
            "prtcareaRw": "20",
            "referenceDate": "2019-12-20",
            "insttCode": "3220000",
            "insttNm": "서울특별시 강남구"
          },
          {
            "fcltyKnd": "초등학교",
            "trgetFcltyNm": "대곡초등학교",
            "rdnmadr": "서울특별시 강남구 남부순환로 3022",
            "lnmadr": "null",
            "latitude": "37.4947119051",
            "hardness": "127.0650264667",
            "longitude": "127.0650264667",
            "institutionNm": "서울특별시 강남구청",
            "cmptncPolcsttnNm": "수서경찰서",
            "cctvYn": "Y",
            "cctvNumber": "2",
            "prtcareaRw": "40",
            "referenceDate": "2019-12-20",
            "insttCode": "3220000",
            "insttNm": "서울특별시 강남구"
          },
          {
            "fcltyKnd": "초등학교",
            "trgetFcltyNm": "대왕초등학교",
            "rdnmadr": "서울특별시 강남구 헌릉로 618길 8",
            "lnmadr": "null",
            "latitude": "37.4646213557",
            "hardness": "127.1055894642",
            "longitude": "127.1055894642",
            "institutionNm": "서울특별시 강남구청",
            "cmptncPolcsttnNm": "수서경찰서",
            "cctvYn": "Y",
            "cctvNumber": "2",
            "prtcareaRw": "6.1",
            "referenceDate": "2019-12-20",
            "insttCode": "3220000",
            "insttNm": "서울특별시 강남구"
          },
          {
            "fcltyKnd": "초등학교",
            "trgetFcltyNm": "대현초등학교",
            "rdnmadr": "서울특별시 강남구 역삼로98길 16",
            "lnmadr": "null",
            "latitude": "37.5037227620",
            "hardness": "127.0635640432",
            "longitude": "127.0635640432",
            "institutionNm": "서울특별시 강남구청",
            "cmptncPolcsttnNm": "수서경찰서",
            "cctvYn": "Y",
            "cctvNumber": "4",
            "prtcareaRw": "5.5",
            "referenceDate": "2019-12-20",
            "insttCode": "3220000",
            "insttNm": "서울특별시 강남구"
          },
          {
            "fcltyKnd": "초등학교",
            "trgetFcltyNm": "도곡초등학교",
            "rdnmadr": "서울특별시 강남구 선릉로64길 33",
            "lnmadr": "null",
            "latitude": "37.4995106013",
            "hardness": "127.0544636040",
            "longitude": "127.0544636040",
            "institutionNm": "서울특별시 강남구청",
            "cmptncPolcsttnNm": "수서경찰서",
            "cctvYn": "Y",
            "cctvNumber": "5",
            "prtcareaRw": "5.3",
            "referenceDate": "2019-12-20",
            "insttCode": "3220000",
            "insttNm": "서울특별시 강남구"
          },
          {
            "fcltyKnd": "초등학교",
            "trgetFcltyNm": "도성초등학교",
            "rdnmadr": "서울특별시 강남구 역삼로 313",
            "lnmadr": "null",
            "latitude": "37.5014628230",
            "hardness": "127.0488737626",
            "longitude": "127.0488737626",
            "institutionNm": "서울특별시 강남구청",
            "cmptncPolcsttnNm": "수서경찰서",
            "cctvYn": "Y",
            "cctvNumber": "2",
            "prtcareaRw": "23.1",
            "referenceDate": "2019-12-20",
            "insttCode": "3220000",
            "insttNm": "서울특별시 강남구"
          },
          {
            "fcltyKnd": "초등학교",
            "trgetFcltyNm": "봉은초등학교",
            "rdnmadr": "서울특별시 강남구 학동로 610",
            "lnmadr": "null",
            "latitude": "37.5200827812",
            "hardness": "127.060981",
            "longitude": "127.060981",
            "institutionNm": "서울특별시 강남구청",
            "cmptncPolcsttnNm": "강남경찰서",
            "cctvYn": "Y",
            "cctvNumber": "3",
            "prtcareaRw": "6",
            "referenceDate": "2019-12-20",
            "insttCode": "3220000",
            "insttNm": "서울특별시 강남구"
          },
          {
            "fcltyKnd": "초등학교",
            "trgetFcltyNm": "삼릉초등학교",
            "rdnmadr": "서울특별시 강남구 봉은사로63길 22",
            "lnmadr": "null",
            "latitude": "37.5132595599",
            "hardness": "127.046914",
            "longitude": "127.046914",
            "institutionNm": "서울특별시 강남구청",
            "cmptncPolcsttnNm": "강남경찰서",
            "cctvYn": "Y",
            "cctvNumber": "4",
            "prtcareaRw": "5.4",
            "referenceDate": "2019-12-20",
            "insttCode": "3220000",
            "insttNm": "서울특별시 강남구"
          },
          {
            "fcltyKnd": "초등학교",
            "trgetFcltyNm": "청담초등학교",
            "rdnmadr": "서울특별시 강남구 압구정로71길 9",
            "lnmadr": "null",
            "latitude": "37.5282817801",
            "hardness": "127.0451533640",
            "longitude": "127.0451533640",
            "institutionNm": "서울특별시 강남구청",
            "cmptncPolcsttnNm": "강남경찰서",
            "cctvYn": "Y",
            "cctvNumber": "6",
            "prtcareaRw": "5.9",
            "referenceDate": "2019-12-20",
            "insttCode": "3220000",
            "insttNm": "서울특별시 강남구"
          },
          {
            "fcltyKnd": "초등학교",
            "trgetFcltyNm": "포이초등학교",
            "rdnmadr": "서울특별시 강남구 개포로22길 87",
            "lnmadr": "null",
            "latitude": "37.4752928730",
            "hardness": "127.0514162216",
            "longitude": "127.0514162216",
            "institutionNm": "서울특별시 강남구청",
            "cmptncPolcsttnNm": "수서경찰서",
            "cctvYn": "Y",
            "cctvNumber": "3",
            "prtcareaRw": "14.5",
            "referenceDate": "2019-12-20",
            "insttCode": "3220000",
            "insttNm": "서울특별시 강남구"
          },
          {
            "fcltyKnd": "초등학교",
            "trgetFcltyNm": "논현초등학교",
            "rdnmadr": "서울특별시 강남구 강남대로120길 33",
            "lnmadr": "null",
            "latitude": "37.5084906566",
            "hardness": "127.0262216669",
            "longitude": "127.0262216669",
            "institutionNm": "서울특별시 강남구청",
            "cmptncPolcsttnNm": "강남경찰서",
            "cctvYn": "Y",
            "cctvNumber": "8",
            "prtcareaRw": "6",
            "referenceDate": "2019-12-20",
            "insttCode": "3220000",
            "insttNm": "서울특별시 강남구"
          },
          {
            "fcltyKnd": "초등학교",
            "trgetFcltyNm": "신구초등학교",
            "rdnmadr": "서울특별시 강남구 압구정로18길 28",
            "lnmadr": "null",
            "latitude": "37.5233612951",
            "hardness": "127.0239915230",
            "longitude": "127.0239915230",
            "institutionNm": "서울특별시 강남구청",
            "cmptncPolcsttnNm": "강남경찰서",
            "cctvYn": "Y",
            "cctvNumber": "8",
            "prtcareaRw": "5.5",
            "referenceDate": "2019-12-20",
            "insttCode": "3220000",
            "insttNm": "서울특별시 강남구"
          },
          {
            "fcltyKnd": "초등학교",
            "trgetFcltyNm": "언북초등학교",
            "rdnmadr": "서울특별시 강남구 삼성로135길 42",
            "lnmadr": "null",
            "latitude": "37.5201260740",
            "hardness": "127.0447140682",
            "longitude": "127.0447140682",
            "institutionNm": "서울특별시 강남구청",
            "cmptncPolcsttnNm": "강남경찰서",
            "cctvYn": "Y",
            "cctvNumber": "8",
            "prtcareaRw": "6",
            "referenceDate": "2019-12-20",
            "insttCode": "3220000",
            "insttNm": "서울특별시 강남구"
          },
          {
            "fcltyKnd": "초등학교",
            "trgetFcltyNm": "영희초등학교",
            "rdnmadr": "서울특별시 강남구 일원로 21",
            "lnmadr": "null",
            "latitude": "37.4923016605",
            "hardness": "127.0811312059",
            "longitude": "127.0811312059",
            "institutionNm": "서울특별시 강남구청",
            "cmptncPolcsttnNm": "수서경찰서",
            "cctvYn": "Y",
            "cctvNumber": "6",
            "prtcareaRw": "9.8",
            "referenceDate": "2019-12-20",
            "insttCode": "3220000",
            "insttNm": "서울특별시 강남구"
          },
          {
            "fcltyKnd": "초등학교",
            "trgetFcltyNm": "일원초등학교",
            "rdnmadr": "서울특별시 강남구 영동대로4길 20",
            "lnmadr": "null",
            "latitude": "37.4897892510",
            "hardness": "127.0763250966",
            "longitude": "127.0763250966",
            "institutionNm": "서울특별시 강남구청",
            "cmptncPolcsttnNm": "수서경찰서",
            "cctvYn": "Y",
            "cctvNumber": "3",
            "prtcareaRw": "7.6",
            "referenceDate": "2019-12-20",
            "insttCode": "3220000",
            "insttNm": "서울특별시 강남구"
          },
          {
            "fcltyKnd": "초등학교",
            "trgetFcltyNm": "학동초등학교",
            "rdnmadr": "서울특별시 강남구 선릉로115길 42",
            "lnmadr": "null",
            "latitude": "37.5122603370",
            "hardness": "127.0395968888",
            "longitude": "127.0395968888",
            "institutionNm": "서울특별시 강남구청",
            "cmptncPolcsttnNm": "강남경찰서",
            "cctvYn": "Y",
            "cctvNumber": "7",
            "prtcareaRw": "5.7",
            "referenceDate": "2019-12-20",
            "insttCode": "3220000",
            "insttNm": "서울특별시 강남구"
          },
          {
            "fcltyKnd": "초등학교",
            "trgetFcltyNm": "개원초등학교",
            "rdnmadr": "서울특별시 강남구 선릉로 29",
            "lnmadr": "null",
            "latitude": "37.4816181495",
            "hardness": "127.0587379216",
            "longitude": "127.0587379216",
            "institutionNm": "서울특별시 강남구청",
            "cmptncPolcsttnNm": "수서경찰서",
            "cctvYn": "Y",
            "cctvNumber": "2",
            "prtcareaRw": "12",
            "referenceDate": "2019-12-20",
            "insttCode": "3220000",
            "insttNm": "서울특별시 강남구"
          },
          {
            "fcltyKnd": "초등학교",
            "trgetFcltyNm": "개일초등학교",
            "rdnmadr": "서울특별시 강남구 개포로 401",
            "lnmadr": "null",
            "latitude": "37.4862137836",
            "hardness": "127.057776",
            "longitude": "127.057776",
            "institutionNm": "서울특별시 강남구청",
            "cmptncPolcsttnNm": "수서경찰서",
            "cctvYn": "Y",
            "cctvNumber": "2",
            "prtcareaRw": "20",
            "referenceDate": "2019-12-20",
            "insttCode": "3220000",
            "insttNm": "서울특별시 강남구"
          },
          {
            "fcltyKnd": "초등학교",
            "trgetFcltyNm": "구룡초등학교",
            "rdnmadr": "서울특별시 강남구 개포로 263",
            "lnmadr": "null",
            "latitude": "37.4811961305",
            "hardness": "127.0517730175",
            "longitude": "127.0517730175",
            "institutionNm": "서울특별시 강남구청",
            "cmptncPolcsttnNm": "수서경찰서",
            "cctvYn": "Y",
            "cctvNumber": "3",
            "prtcareaRw": "14",
            "referenceDate": "2019-12-20",
            "insttCode": "3220000",
            "insttNm": "서울특별시 강남구"
          },
          {
            "fcltyKnd": "초등학교",
            "trgetFcltyNm": "대도초등학교",
            "rdnmadr": "서울특별시 강남구 선릉로 209",
            "lnmadr": "null",
            "latitude": "37.4926454265",
            "hardness": "127.0533775880",
            "longitude": "127.0533775880",
            "institutionNm": "서울특별시 강남구청",
            "cmptncPolcsttnNm": "수서경찰서",
            "cctvYn": "Y",
            "cctvNumber": "2",
            "prtcareaRw": "28.7",
            "referenceDate": "2019-12-20",
            "insttCode": "3220000",
            "insttNm": "서울특별시 강남구"
          },
          {
            "fcltyKnd": "초등학교",
            "trgetFcltyNm": "대모초등학교",
            "rdnmadr": "서울특별시 강남구 광평로20길 27",
            "lnmadr": "null",
            "latitude": "37.4805995343",
            "hardness": "127.0859937141",
            "longitude": "127.0859937141",
            "institutionNm": "서울특별시 강남구청",
            "cmptncPolcsttnNm": "수서경찰서",
            "cctvYn": "Y",
            "cctvNumber": "2",
            "prtcareaRw": "14.5",
            "referenceDate": "2019-12-20",
            "insttCode": "3220000",
            "insttNm": "서울특별시 강남구"
          },
          {
            "fcltyKnd": "초등학교",
            "trgetFcltyNm": "율현초등학교",
            "rdnmadr": "서울특별시 강남구 밤고개로21길 15",
            "lnmadr": "null",
            "latitude": "37.474559",
            "hardness": "127.108267",
            "longitude": "127.108267",
            "institutionNm": "서울특별시 강남구청",
            "cmptncPolcsttnNm": "수서경찰서",
            "cctvYn": "Y",
            "cctvNumber": "1",
            "prtcareaRw": "8",
            "referenceDate": "2019-12-20",
            "insttCode": "3220000",
            "insttNm": "서울특별시 강남구"
          },
          {
            "fcltyKnd": "초등학교",
            "trgetFcltyNm": "자곡초등학교",
            "rdnmadr": "서울특별시 강남구 자곡로 150",
            "lnmadr": "null",
            "latitude": "37.472191",
            "hardness": "127.0995995421",
            "longitude": "127.0995995421",
            "institutionNm": "서울특별시 강남구청",
            "cmptncPolcsttnNm": "수서경찰서",
            "cctvYn": "Y",
            "cctvNumber": "2",
            "prtcareaRw": "25",
            "referenceDate": "2019-12-20",
            "insttCode": "3220000",
            "insttNm": "서울특별시 강남구"
          },
          {
            "fcltyKnd": "특수학교",
            "trgetFcltyNm": "밀알학교",
            "rdnmadr": "서울특별시 강남구 일원로 90",
            "lnmadr": "null",
            "latitude": "37.4857813187",
            "hardness": "127.0820739268",
            "longitude": "127.0820739268",
            "institutionNm": "서울특별시 강남구청",
            "cmptncPolcsttnNm": "수서경찰서",
            "cctvYn": "Y",
            "cctvNumber": "3",
            "prtcareaRw": "14.4",
            "referenceDate": "2019-12-20",
            "insttCode": "3220000",
            "insttNm": "서울특별시 강남구"
          },
          {
            "fcltyKnd": "특수학교",
            "trgetFcltyNm": "정애학교",
            "rdnmadr": "서울특별시 강남구 봉은사로81길 16",
            "lnmadr": "null",
            "latitude": "37.514363",
            "hardness": "127.054425",
            "longitude": "127.054425",
            "institutionNm": "서울특별시 강남구청",
            "cmptncPolcsttnNm": "강남경찰서",
            "cctvYn": "Y",
            "cctvNumber": "2",
            "prtcareaRw": "6",
            "referenceDate": "2019-12-20",
            "insttCode": "3220000",
            "insttNm": "서울특별시 강남구"
          },
          {
            "fcltyKnd": "특수학교",
            "trgetFcltyNm": "서울아카데미(외국인)",
            "rdnmadr": "서울특별시 강남구 삼성로64길 16",
            "lnmadr": "null",
            "latitude": "37.4999611921",
            "hardness": "127.061603",
            "longitude": "127.061603",
            "institutionNm": "서울특별시 강남구청",
            "cmptncPolcsttnNm": "수서경찰서",
            "cctvYn": "Y",
            "cctvNumber": "2",
            "prtcareaRw": "19.7",
            "referenceDate": "2019-12-20",
            "insttCode": "3220000",
            "insttNm": "서울특별시 강남구"
          },
          {
            "fcltyKnd": "어린이집",
            "trgetFcltyNm": "연화어린이집",
            "rdnmadr": "서울특별시 강남구 학동로 43길 17",
            "lnmadr": "null",
            "latitude": "37.517216",
            "hardness": "127.037152",
            "longitude": "127.037152",
            "institutionNm": "서울특별시 강남구청",
            "cmptncPolcsttnNm": "강남경찰서",
            "cctvYn": "Y",
            "cctvNumber": "1",
            "prtcareaRw": "6",
            "referenceDate": "2019-12-20",
            "insttCode": "3220000",
            "insttNm": "서울특별시 강남구"
          },
          {
            "fcltyKnd": "어린이집",
            "trgetFcltyNm": "한별어린이집",
            "rdnmadr": "서울특별시 강남구 봉은사로82길 23",
            "lnmadr": "null",
            "latitude": "37.511759",
            "hardness": "127.0555131179",
            "longitude": "127.0555131179",
            "institutionNm": "서울특별시 강남구청",
            "cmptncPolcsttnNm": "강남경찰서",
            "cctvYn": "Y",
            "cctvNumber": "1",
            "prtcareaRw": "6",
            "referenceDate": "2019-12-20",
            "insttCode": "3220000",
            "insttNm": "서울특별시 강남구"
          },
          {
            "fcltyKnd": "어린이집",
            "trgetFcltyNm": "삼성어린이집",
            "rdnmadr": "서울특별시 강남구 도곡로78길 22",
            "lnmadr": "null",
            "latitude": "37.4966360899",
            "hardness": "127.058851",
            "longitude": "127.058851",
            "institutionNm": "서울특별시 강남구청",
            "cmptncPolcsttnNm": "수서경찰서",
            "cctvYn": "Y",
            "cctvNumber": "2",
            "prtcareaRw": "6",
            "referenceDate": "2019-12-20",
            "insttCode": "3220000",
            "insttNm": "서울특별시 강남구"
          },
          {
            "fcltyKnd": "어린이집",
            "trgetFcltyNm": "오르다어린이집",
            "rdnmadr": "서울특별시 강남구 봉은사로73길 3-4",
            "lnmadr": "null",
            "latitude": "37.5127967751",
            "hardness": "127.0505144450",
            "longitude": "127.0505144450",
            "institutionNm": "서울특별시 강남구청",
            "cmptncPolcsttnNm": "강남경찰서",
            "cctvYn": "Y",
            "cctvNumber": "2",
            "prtcareaRw": "10",
            "referenceDate": "2019-12-20",
            "insttCode": "3220000",
            "insttNm": "서울특별시 강남구"
          },
          {
            "fcltyKnd": "어린이집",
            "trgetFcltyNm": "선릉삼성어린이집",
            "rdnmadr": "서울특별시 강남구 선릉로100길 48",
            "lnmadr": "null",
            "latitude": "37.506634",
            "hardness": "127.051164",
            "longitude": "127.051164",
            "institutionNm": "서울특별시 강남구청",
            "cmptncPolcsttnNm": "강남경찰서",
            "cctvYn": "Y",
            "cctvNumber": "1",
            "prtcareaRw": "12",
            "referenceDate": "2019-12-20",
            "insttCode": "3220000",
            "insttNm": "서울특별시 강남구"
          },
          {
            "fcltyKnd": "어린이집",
            "trgetFcltyNm": "성모어린이집",
            "rdnmadr": "서울특별시 강남구 강남대로124길 65",
            "lnmadr": "null",
            "latitude": "37.5110277338",
            "hardness": "127.026898",
            "longitude": "127.026898",
            "institutionNm": "서울특별시 강남구청",
            "cmptncPolcsttnNm": "강남경찰서",
            "cctvYn": "Y",
            "cctvNumber": "2",
            "prtcareaRw": "6",
            "referenceDate": "2019-12-20",
            "insttCode": "3220000",
            "insttNm": "서울특별시 강남구"
          },
          {
            "fcltyKnd": "어린이집",
            "trgetFcltyNm": "준현어린이집",
            "rdnmadr": "서울특별시 강남구 선릉로148길 48-6",
            "lnmadr": "null",
            "latitude": "37.5226241543",
            "hardness": "127.043338",
            "longitude": "127.043338",
            "institutionNm": "서울특별시 강남구청",
            "cmptncPolcsttnNm": "강남경찰서",
            "cctvYn": "Y",
            "cctvNumber": "1",
            "prtcareaRw": "4",
            "referenceDate": "2019-12-20",
            "insttCode": "3220000",
            "insttNm": "서울특별시 강남구"
          },
          {
            "fcltyKnd": "어린이집",
            "trgetFcltyNm": "자람어린이집",
            "rdnmadr": "서울특별시 강남구 일원로5길 29",
            "lnmadr": "null",
            "latitude": "37.491666",
            "hardness": "127.082926",
            "longitude": "127.082926",
            "institutionNm": "서울특별시 강남구청",
            "cmptncPolcsttnNm": "수서경찰서",
            "cctvYn": "Y",
            "cctvNumber": "1",
            "prtcareaRw": "8",
            "referenceDate": "2019-12-20",
            "insttCode": "3220000",
            "insttNm": "서울특별시 강남구"
          },
          {
            "fcltyKnd": "어린이집",
            "trgetFcltyNm": "목련어린이집",
            "rdnmadr": "서울특별시 강남구 개포로 617-8",
            "lnmadr": "null",
            "latitude": "37.494007",
            "hardness": "127.077734",
            "longitude": "127.077734",
            "institutionNm": "서울특별시 강남구청",
            "cmptncPolcsttnNm": "수서경찰서",
            "cctvYn": "Y",
            "cctvNumber": "1",
            "prtcareaRw": "10",
            "referenceDate": "2019-12-20",
            "insttCode": "3220000",
            "insttNm": "서울특별시 강남구"
          },
          {
            "fcltyKnd": "어린이집",
            "trgetFcltyNm": "대치어린이집",
            "rdnmadr": "서울특별시 강남구 영동대로65길 11",
            "lnmadr": "null",
            "latitude": "37.5018547840",
            "hardness": "127.065542",
            "longitude": "127.065542",
            "institutionNm": "서울특별시 강남구청",
            "cmptncPolcsttnNm": "수서경찰서",
            "cctvYn": "Y",
            "cctvNumber": "1",
            "prtcareaRw": "12",
            "referenceDate": "2019-12-20",
            "insttCode": "3220000",
            "insttNm": "서울특별시 강남구"
          },
          {
            "fcltyKnd": "어린이집",
            "trgetFcltyNm": "한티어린이집",
            "rdnmadr": "서울특별시 강남구 영동대로57길 7, 대치문화복지회관 3층",
            "lnmadr": "null",
            "latitude": "37.4999546729",
            "hardness": "127.066938",
            "longitude": "127.066938",
            "institutionNm": "서울특별시 강남구청",
            "cmptncPolcsttnNm": "수서경찰서",
            "cctvYn": "Y",
            "cctvNumber": "1",
            "prtcareaRw": "8",
            "referenceDate": "2019-12-20",
            "insttCode": "3220000",
            "insttNm": "서울특별시 강남구"
          },
          {
            "fcltyKnd": "어린이집",
            "trgetFcltyNm": "킹스키즈어린이집",
            "rdnmadr": "서울특별시 강남구 도곡로73길 31-1",
            "lnmadr": "null",
            "latitude": "37.4998341260",
            "hardness": "127.056227",
            "longitude": "127.056227",
            "institutionNm": "서울특별시 강남구청",
            "cmptncPolcsttnNm": "수서경찰서",
            "cctvYn": "Y",
            "cctvNumber": "1",
            "prtcareaRw": "6",
            "referenceDate": "2019-12-20",
            "insttCode": "3220000",
            "insttNm": "서울특별시 강남구"
          },
          {
            "fcltyKnd": "어린이집",
            "trgetFcltyNm": "선재어린이집",
            "rdnmadr": "서울특별시 강남구 삼성로71길 31",
            "lnmadr": "null",
            "latitude": "37.5014775107",
            "hardness": "127.0563559282",
            "longitude": "127.0563559282",
            "institutionNm": "서울특별시 강남구청",
            "cmptncPolcsttnNm": "수서경찰서",
            "cctvYn": "Y",
            "cctvNumber": "1",
            "prtcareaRw": "6",
            "referenceDate": "2019-12-20",
            "insttCode": "3220000",
            "insttNm": "서울특별시 강남구"
          },
          {
            "fcltyKnd": "어린이집",
            "trgetFcltyNm": "성아어린이집",
            "rdnmadr": "서울특별시 강남구 논현로32길 16",
            "lnmadr": "null",
            "latitude": "37.484042",
            "hardness": "127.043583",
            "longitude": "127.043583",
            "institutionNm": "서울특별시 강남구청",
            "cmptncPolcsttnNm": "수서경찰서",
            "cctvYn": "Y",
            "cctvNumber": "1",
            "prtcareaRw": "6",
            "referenceDate": "2019-12-20",
            "insttCode": "3220000",
            "insttNm": "서울특별시 강남구"
          },
          {
            "fcltyKnd": "어린이집",
            "trgetFcltyNm": "청수어린이집",
            "rdnmadr": "서울특별시 강남구 압구정로79길 26",
            "lnmadr": "null",
            "latitude": "37.525052",
            "hardness": "127.049284",
            "longitude": "127.049284",
            "institutionNm": "서울특별시 강남구청",
            "cmptncPolcsttnNm": "강남경찰서",
            "cctvYn": "Y",
            "cctvNumber": "3",
            "prtcareaRw": "8",
            "referenceDate": "2019-12-20",
            "insttCode": "3220000",
            "insttNm": "서울특별시 강남구"
          },
          {
            "fcltyKnd": "어린이집",
            "trgetFcltyNm": "튼튼영재어린이집",
            "rdnmadr": "서울특별시 강남구 학동로101길 26, 삼익상가3층",
            "lnmadr": "null",
            "latitude": "37.5224450698",
            "hardness": "127.0576205786",
            "longitude": "127.0576205786",
            "institutionNm": "서울특별시 강남구청",
            "cmptncPolcsttnNm": "강남경찰서",
            "cctvYn": "Y",
            "cctvNumber": "3",
            "prtcareaRw": "6",
            "referenceDate": "2019-12-20",
            "insttCode": "3220000",
            "insttNm": "서울특별시 강남구"
          },
          {
            "fcltyKnd": "어린이집",
            "trgetFcltyNm": "강남구청어린이집",
            "rdnmadr": "서울특별시 강남구 학동로 426",
            "lnmadr": "null",
            "latitude": "37.5179663586",
            "hardness": "127.0470610826",
            "longitude": "127.0470610826",
            "institutionNm": "서울특별시 강남구청",
            "cmptncPolcsttnNm": "강남경찰서",
            "cctvYn": "Y",
            "cctvNumber": "1",
            "prtcareaRw": "8",
            "referenceDate": "2019-12-20",
            "insttCode": "3220000",
            "insttNm": "서울특별시 강남구"
          },
          {
            "fcltyKnd": "어린이집",
            "trgetFcltyNm": "구민회관어린이집",
            "rdnmadr": "서울특별시 강남구 삼성로 154",
            "lnmadr": "null",
            "latitude": "37.4938869965",
            "hardness": "127.0642703746",
            "longitude": "127.0642703746",
            "institutionNm": "서울특별시 강남구청",
            "cmptncPolcsttnNm": "수서경찰서",
            "cctvYn": "Y",
            "cctvNumber": "1",
            "prtcareaRw": "30",
            "referenceDate": "2019-12-20",
            "insttCode": "3220000",
            "insttNm": "서울특별시 강남구"
          },
          {
            "fcltyKnd": "유치원",
            "trgetFcltyNm": "럭키유치원",
            "rdnmadr": "서울특별시 강남구 논현로 213",
            "lnmadr": "null",
            "latitude": "37.4914141895",
            "hardness": "127.0409970785",
            "longitude": "127.0409970785",
            "institutionNm": "서울특별시 강남구청",
            "cmptncPolcsttnNm": "수서경찰서",
            "cctvYn": "Y",
            "cctvNumber": "2",
            "prtcareaRw": "6",
            "referenceDate": "2019-12-20",
            "insttCode": "3220000",
            "insttNm": "서울특별시 강남구"
          },
          {
            "fcltyKnd": "유치원",
            "trgetFcltyNm": "반디유치원",
            "rdnmadr": "서울특별시 강남구 광평로47길 17",
            "lnmadr": "null",
            "latitude": "37.4879098215",
            "hardness": "127.0981866623",
            "longitude": "127.0981866623",
            "institutionNm": "서울특별시 강남구청",
            "cmptncPolcsttnNm": "수서경찰서",
            "cctvYn": "Y",
            "cctvNumber": "2",
            "prtcareaRw": "9.6",
            "referenceDate": "2019-12-20",
            "insttCode": "3220000",
            "insttNm": "서울특별시 강남구"
          },
          {
            "fcltyKnd": "유치원",
            "trgetFcltyNm": "신우주유치원",
            "rdnmadr": "서울특별시 강남구 일원로 120",
            "lnmadr": "null",
            "latitude": "37.4852006505",
            "hardness": "127.0826748096",
            "longitude": "127.0826748096",
            "institutionNm": "서울특별시 강남구청",
            "cmptncPolcsttnNm": "수서경찰서",
            "cctvYn": "Y",
            "cctvNumber": "1",
            "prtcareaRw": "14.4",
            "referenceDate": "2019-12-20",
            "insttCode": "3220000",
            "insttNm": "서울특별시 강남구"
          },
          {
            "fcltyKnd": "유치원",
            "trgetFcltyNm": "초원유치원",
            "rdnmadr": "서울특별시 강남구 논현로14길 17",
            "lnmadr": "null",
            "latitude": "37.475915",
            "hardness": "127.048578",
            "longitude": "127.048578",
            "institutionNm": "서울특별시 강남구청",
            "cmptncPolcsttnNm": "수서경찰서",
            "cctvYn": "Y",
            "cctvNumber": "2",
            "prtcareaRw": "9.4",
            "referenceDate": "2019-12-20",
            "insttCode": "3220000",
            "insttNm": "서울특별시 강남구"
          },
          {
            "fcltyKnd": "유치원",
            "trgetFcltyNm": "성결유치원",
            "rdnmadr": "서울특별시 강남구 언주로121길 5",
            "lnmadr": "null",
            "latitude": "37.511421",
            "hardness": "127.035354",
            "longitude": "127.035354",
            "institutionNm": "서울특별시 강남구청",
            "cmptncPolcsttnNm": "강남경찰서",
            "cctvYn": "Y",
            "cctvNumber": "4",
            "prtcareaRw": "6",
            "referenceDate": "2019-12-20",
            "insttCode": "3220000",
            "insttNm": "서울특별시 강남구"
          },
          {
            "fcltyKnd": "유치원",
            "trgetFcltyNm": "하늘빛유치원",
            "rdnmadr": "서울특별시 강남구 양재대로55길 10",
            "lnmadr": "null",
            "latitude": "37.493156",
            "hardness": "127.090993",
            "longitude": "127.090993",
            "institutionNm": "서울특별시 강남구청",
            "cmptncPolcsttnNm": "수서경찰서",
            "cctvYn": "Y",
            "cctvNumber": "1",
            "prtcareaRw": "11.5",
            "referenceDate": "2019-12-20",
            "insttCode": "3220000",
            "insttNm": "서울특별시 강남구"
          },
          {
            "fcltyKnd": "유치원",
            "trgetFcltyNm": "도곡렉슬유치원",
            "rdnmadr": "서울특별시 강남구 선릉로 217",
            "lnmadr": "null",
            "latitude": "37.4943212397",
            "hardness": "127.0535099547",
            "longitude": "127.0535099547",
            "institutionNm": "서울특별시 강남구청",
            "cmptncPolcsttnNm": "수서경찰서",
            "cctvYn": "Y",
            "cctvNumber": "2",
            "prtcareaRw": "25",
            "referenceDate": "2019-12-20",
            "insttCode": "3220000",
            "insttNm": "서울특별시 강남구"
          },
          {
            "fcltyKnd": "유치원",
            "trgetFcltyNm": "역삼초등학교병설유치원",
            "rdnmadr": "서울특별시 강남구 강남대로66길 21",
            "lnmadr": "null",
            "latitude": "37.4931611542",
            "hardness": "127.0326030259",
            "longitude": "127.0326030259",
            "institutionNm": "서울특별시 강남구청",
            "cmptncPolcsttnNm": "수서경찰서",
            "cctvYn": "Y",
            "cctvNumber": "1",
            "prtcareaRw": "11.8",
            "referenceDate": "2019-12-20",
            "insttCode": "3220000",
            "insttNm": "서울특별시 강남구"
          },
          {
            "fcltyKnd": "유치원",
            "trgetFcltyNm": "개포초등학교유치원",
            "rdnmadr": "서울특별시 강남구 영동대로3길 45",
            "lnmadr": "null",
            "latitude": "37.4868054401",
            "hardness": "127.0699765891",
            "longitude": "127.0699765891",
            "institutionNm": "서울특별시 강남구청",
            "cmptncPolcsttnNm": "수서경찰서",
            "cctvYn": "Y",
            "cctvNumber": "1",
            "prtcareaRw": "15",
            "referenceDate": "2019-12-20",
            "insttCode": "3220000",
            "insttNm": "서울특별시 강남구"
          },
          {
            "fcltyKnd": "유치원",
            "trgetFcltyNm": "대현초등학교병설유치원",
            "rdnmadr": "서울특별시 강남구 역삼로98길 16",
            "lnmadr": "null",
            "latitude": "37.5037227620",
            "hardness": "127.0635640432",
            "longitude": "127.0635640432",
            "institutionNm": "서울특별시 강남구청",
            "cmptncPolcsttnNm": "수서경찰서",
            "cctvYn": "Y",
            "cctvNumber": "1",
            "prtcareaRw": "5.5",
            "referenceDate": "2019-12-20",
            "insttCode": "3220000",
            "insttNm": "서울특별시 강남구"
          },
          {
            "fcltyKnd": "유치원",
            "trgetFcltyNm": "수서초등학교병설유치원",
            "rdnmadr": "서울특별시 강남구 광평로51길 46",
            "lnmadr": "null",
            "latitude": "37.4911505764",
            "hardness": "127.101549",
            "longitude": "127.101549",
            "institutionNm": "서울특별시 강남구청",
            "cmptncPolcsttnNm": "수서경찰서",
            "cctvYn": "Y",
            "cctvNumber": "1",
            "prtcareaRw": "6.5",
            "referenceDate": "2019-12-20",
            "insttCode": "3220000",
            "insttNm": "서울특별시 강남구"
          },
          {
            "fcltyKnd": "유치원",
            "trgetFcltyNm": "유정유치원",
            "rdnmadr": "서울특별시 강남구 광평로34길 17",
            "lnmadr": "null",
            "latitude": "37.4830073857",
            "hardness": "127.0949420948",
            "longitude": "127.0949420948",
            "institutionNm": "서울특별시 강남구청",
            "cmptncPolcsttnNm": "수서경찰서",
            "cctvYn": "N",
            "cctvNumber": "null",
            "prtcareaRw": "null",
            "referenceDate": "2019-12-20",
            "insttCode": "3220000",
            "insttNm": "서울특별시 강남구"
          },
          {
            "fcltyKnd": "어린이집",
            "trgetFcltyNm": "강남동산어린이집",
            "rdnmadr": "서울특별시 강남구 개포로 257",
            "lnmadr": "null",
            "latitude": "37.479431",
            "hardness": "127.0504286463",
            "longitude": "127.0504286463",
            "institutionNm": "서울특별시 강남구청",
            "cmptncPolcsttnNm": "수서경찰서",
            "cctvYn": "Y",
            "cctvNumber": "1",
            "prtcareaRw": "6",
            "referenceDate": "2019-12-20",
            "insttCode": "3220000",
            "insttNm": "서울특별시 강남구"
          },
          {
            "fcltyKnd": "어린이집",
            "trgetFcltyNm": "도토리소풍넥슨어린이집",
            "rdnmadr": "서울특별시 강남구 봉은사로68길 27",
            "lnmadr": "null",
            "latitude": "37.5104322131",
            "hardness": "127.051243",
            "longitude": "127.051243",
            "institutionNm": "서울특별시 강남구청",
            "cmptncPolcsttnNm": "강남경찰서",
            "cctvYn": "Y",
            "cctvNumber": "1",
            "prtcareaRw": "12",
            "referenceDate": "2019-12-20",
            "insttCode": "3220000",
            "insttNm": "서울특별시 강남구"
          },
          {
            "fcltyKnd": "어린이집",
            "trgetFcltyNm": "압구정아람어린이집",
            "rdnmadr": "서울특별시 강남구 압구정로 311",
            "lnmadr": "null",
            "latitude": "37.5293482238",
            "hardness": "127.0356145558",
            "longitude": "127.0356145558",
            "institutionNm": "서울특별시 강남구청",
            "cmptncPolcsttnNm": "강남경찰서",
            "cctvYn": "Y",
            "cctvNumber": "3",
            "prtcareaRw": "30",
            "referenceDate": "2019-12-20",
            "insttCode": "3220000",
            "insttNm": "서울특별시 강남구"
          },
          {
            "fcltyKnd": "어린이집",
            "trgetFcltyNm": "예지어린이집",
            "rdnmadr": "서울특별시 강남구 논현로2길 40",
            "lnmadr": "null",
            "latitude": "37.4735223605",
            "hardness": "127.0535086893",
            "longitude": "127.0535086893",
            "institutionNm": "서울특별시 강남구청",
            "cmptncPolcsttnNm": "수서경찰서",
            "cctvYn": "Y",
            "cctvNumber": "1",
            "prtcareaRw": "40",
            "referenceDate": "2019-12-20",
            "insttCode": "3220000",
            "insttNm": "서울특별시 강남구"
          },
          {
            "fcltyKnd": "어린이집",
            "trgetFcltyNm": "강남어린이집",
            "rdnmadr": "서울특별시 강남구 개포로109길 9",
            "lnmadr": "null",
            "latitude": "37.495751",
            "hardness": "127.075096",
            "longitude": "127.075096",
            "institutionNm": "서울특별시 강남구청",
            "cmptncPolcsttnNm": "수서경찰서",
            "cctvYn": "Y",
            "cctvNumber": "1",
            "prtcareaRw": "20",
            "referenceDate": "2019-12-20",
            "insttCode": "3220000",
            "insttNm": "서울특별시 강남구"
          },
          {
            "fcltyKnd": "어린이집",
            "trgetFcltyNm": "방죽어린이집",
            "rdnmadr": "서울특별시 강남구 밤고개로24길 75",
            "lnmadr": "null",
            "latitude": "37.4699201969",
            "hardness": "127.104503",
            "longitude": "127.104503",
            "institutionNm": "서울특별시 강남구청",
            "cmptncPolcsttnNm": "수서경찰서",
            "cctvYn": "Y",
            "cctvNumber": "1",
            "prtcareaRw": "8",
            "referenceDate": "2019-12-20",
            "insttCode": "3220000",
            "insttNm": "서울특별시 강남구"
          },
          {
            "fcltyKnd": "어린이집",
            "trgetFcltyNm": "푸른어린이집",
            "rdnmadr": "서울특별시 강남구 자곡로7길 8-1",
            "lnmadr": "null",
            "latitude": "37.4735607837",
            "hardness": "127.0998274586",
            "longitude": "127.0998274586",
            "institutionNm": "서울특별시 강남구청",
            "cmptncPolcsttnNm": "수서경찰서",
            "cctvYn": "Y",
            "cctvNumber": "2",
            "prtcareaRw": "8",
            "referenceDate": "2019-12-20",
            "insttCode": "3220000",
            "insttNm": "서울특별시 강남구"
          },
          {
            "fcltyKnd": "어린이집",
            "trgetFcltyNm": "바롬어린이집",
            "rdnmadr": "서울특별시 강남구 언주로164길 36",
            "lnmadr": "null",
            "latitude": "37.525305",
            "hardness": "127.036309",
            "longitude": "127.036309",
            "institutionNm": "서울특별시 강남구청",
            "cmptncPolcsttnNm": "강남경찰서",
            "cctvYn": "Y",
            "cctvNumber": "1",
            "prtcareaRw": "6",
            "referenceDate": "2019-12-20",
            "insttCode": "3220000",
            "insttNm": "서울특별시 강남구"
          },
          {
            "fcltyKnd": "어린이집",
            "trgetFcltyNm": "역삼가애어린이집",
            "rdnmadr": "서울특별시 강남구 도곡로37길 15",
            "lnmadr": "null",
            "latitude": "37.494809",
            "hardness": "127.044725",
            "longitude": "127.044725",
            "institutionNm": "서울특별시 강남구청",
            "cmptncPolcsttnNm": "수서경찰서",
            "cctvYn": "Y",
            "cctvNumber": "2",
            "prtcareaRw": "12",
            "referenceDate": "2019-12-20",
            "insttCode": "3220000",
            "insttNm": "서울특별시 강남구"
          },
          {
            "fcltyKnd": "어린이집",
            "trgetFcltyNm": "아이뜰어린이집",
            "rdnmadr": "서울특별시 강남구 개포로22길 39-11",
            "lnmadr": "null",
            "latitude": "37.477164",
            "hardness": "127.050117",
            "longitude": "127.050117",
            "institutionNm": "서울특별시 강남구청",
            "cmptncPolcsttnNm": "수서경찰서",
            "cctvYn": "Y",
            "cctvNumber": "1",
            "prtcareaRw": "8",
            "referenceDate": "2019-12-20",
            "insttCode": "3220000",
            "insttNm": "서울특별시 강남구"
          },
          {
            "fcltyKnd": "어린이집",
            "trgetFcltyNm": "해맑은어린이집",
            "rdnmadr": "서울특별시 강남구 개포로36길 14",
            "lnmadr": "null",
            "latitude": "37.478521",
            "hardness": "127.0513054039",
            "longitude": "127.0513054039",
            "institutionNm": "서울특별시 강남구청",
            "cmptncPolcsttnNm": "수서경찰서",
            "cctvYn": "Y",
            "cctvNumber": "1",
            "prtcareaRw": "6",
            "referenceDate": "2019-12-20",
            "insttCode": "3220000",
            "insttNm": "서울특별시 강남구"
          },
          {
            "fcltyKnd": "어린이집",
            "trgetFcltyNm": "대청어린이집",
            "rdnmadr": "서울특별시 강남구 양재대로37길 19",
            "lnmadr": "null",
            "latitude": "37.490853",
            "hardness": "127.083513",
            "longitude": "127.083513",
            "institutionNm": "서울특별시 강남구청",
            "cmptncPolcsttnNm": "수서경찰서",
            "cctvYn": "Y",
            "cctvNumber": "1",
            "prtcareaRw": "6",
            "referenceDate": "2019-12-20",
            "insttCode": "3220000",
            "insttNm": "서울특별시 강남구"
          },
          {
            "fcltyKnd": "어린이집",
            "trgetFcltyNm": "충현어린이집",
            "rdnmadr": "서울특별시 강남구 테헤란로27길 40",
            "lnmadr": "null",
            "latitude": "37.5053268519",
            "hardness": "127.0376162797",
            "longitude": "127.0376162797",
            "institutionNm": "서울특별시 강남구청",
            "cmptncPolcsttnNm": "수서경찰서",
            "cctvYn": "Y",
            "cctvNumber": "2",
            "prtcareaRw": "12",
            "referenceDate": "2019-12-20",
            "insttCode": "3220000",
            "insttNm": "서울특별시 강남구"
          },
          {
            "fcltyKnd": "어린이집",
            "trgetFcltyNm": "세곡햇빛어린이집",
            "rdnmadr": "서울특별시 강남구 자곡로 260",
            "lnmadr": "null",
            "latitude": "37.476549",
            "hardness": "127.111611",
            "longitude": "127.111611",
            "institutionNm": "서울특별시 강남구청",
            "cmptncPolcsttnNm": "수서경찰서",
            "cctvYn": "N",
            "cctvNumber": "0",
            "prtcareaRw": "8",
            "referenceDate": "2019-12-20",
            "insttCode": "3220000",
            "insttNm": "서울특별시 강남구"
          },
          {
            "fcltyKnd": "어린이집",
            "trgetFcltyNm": "한울어린이집",
            "rdnmadr": "서울특별시 강남구 삼성로51길 25",
            "lnmadr": "null",
            "latitude": "37.4959069847",
            "hardness": "127.0610017328",
            "longitude": "127.0610017328",
            "institutionNm": "서울특별시 강남구청",
            "cmptncPolcsttnNm": "수서경찰서",
            "cctvYn": "Y",
            "cctvNumber": "1",
            "prtcareaRw": "8",
            "referenceDate": "2019-12-20",
            "insttCode": "3220000",
            "insttNm": "서울특별시 강남구"
          },
          {
            "fcltyKnd": "어린이집",
            "trgetFcltyNm": "미담어린이집",
            "rdnmadr": "서울특별시 강남구 일원로 115",
            "lnmadr": "null",
            "latitude": "37.4840208691",
            "hardness": "127.0844599444",
            "longitude": "127.0844599444",
            "institutionNm": "서울특별시 강남구청",
            "cmptncPolcsttnNm": "수서경찰서",
            "cctvYn": "Y",
            "cctvNumber": "null",
            "prtcareaRw": "null",
            "referenceDate": "2019-12-20",
            "insttCode": "3220000",
            "insttNm": "서울특별시 강남구"
          },
          {
            "fcltyKnd": "어린이집",
            "trgetFcltyNm": "아이앤어린이집",
            "rdnmadr": "서울특별시 강남구 봉은사로68길 35-2",
            "lnmadr": "null",
            "latitude": "37.5100283144",
            "hardness": "127.0518426910",
            "longitude": "127.0518426910",
            "institutionNm": "서울특별시 강남구청",
            "cmptncPolcsttnNm": "강남경찰서",
            "cctvYn": "Y",
            "cctvNumber": "null",
            "prtcareaRw": "null",
            "referenceDate": "2019-12-20",
            "insttCode": "3220000",
            "insttNm": "서울특별시 강남구"
          },
          {
            "fcltyKnd": "초등학교",
            "trgetFcltyNm": "대진초등학교",
            "rdnmadr": "서울특별시 강남구 개포로109길 74",
            "lnmadr": "null",
            "latitude": "37.497027",
            "hardness": "127.0780784792",
            "longitude": "127.0780784792",
            "institutionNm": "서울특별시 강남구청",
            "cmptncPolcsttnNm": "수서경찰서",
            "cctvYn": "Y",
            "cctvNumber": "3",
            "prtcareaRw": "9",
            "referenceDate": "2019-12-20",
            "insttCode": "3220000",
            "insttNm": "서울특별시 강남구"
          },
          {
            "fcltyKnd": "초등학교",
            "trgetFcltyNm": "수서초등학교",
            "rdnmadr": "서울특별시 강남구 광평로51길 46",
            "lnmadr": "null",
            "latitude": "37.4911505764",
            "hardness": "127.101549",
            "longitude": "127.101549",
            "institutionNm": "서울특별시 강남구청",
            "cmptncPolcsttnNm": "수서경찰서",
            "cctvYn": "Y",
            "cctvNumber": "5",
            "prtcareaRw": "6.5",
            "referenceDate": "2019-12-20",
            "insttCode": "3220000",
            "insttNm": "서울특별시 강남구"
          },
          {
            "fcltyKnd": "초등학교",
            "trgetFcltyNm": "압구정초등학교",
            "rdnmadr": "서울특별시 강남구 압구정로39길 29",
            "lnmadr": "null",
            "latitude": "37.5317390226",
            "hardness": "127.0308412892",
            "longitude": "127.0308412892",
            "institutionNm": "서울특별시 강남구청",
            "cmptncPolcsttnNm": "강남경찰서",
            "cctvYn": "Y",
            "cctvNumber": "2",
            "prtcareaRw": "8.9",
            "referenceDate": "2019-12-20",
            "insttCode": "3220000",
            "insttNm": "서울특별시 강남구"
          },
          {
            "fcltyKnd": "초등학교",
            "trgetFcltyNm": "언주초등학교",
            "rdnmadr": "서울특별시 강남구 남부순환로363길 19",
            "lnmadr": "null",
            "latitude": "37.4863230777",
            "hardness": "127.036781",
            "longitude": "127.036781",
            "institutionNm": "서울특별시 강남구청",
            "cmptncPolcsttnNm": "수서경찰서",
            "cctvYn": "Y",
            "cctvNumber": "5",
            "prtcareaRw": "7.7",
            "referenceDate": "2019-12-20",
            "insttCode": "3220000",
            "insttNm": "서울특별시 강남구"
          },
          {
            "fcltyKnd": "초등학교",
            "trgetFcltyNm": "역삼초등학교",
            "rdnmadr": "서울특별시 강남구 강남대로66길 21",
            "lnmadr": "null",
            "latitude": "37.4931611542",
            "hardness": "127.0326030259",
            "longitude": "127.0326030259",
            "institutionNm": "서울특별시 강남구청",
            "cmptncPolcsttnNm": "수서경찰서",
            "cctvYn": "Y",
            "cctvNumber": "7",
            "prtcareaRw": "6.9",
            "referenceDate": "2019-12-20",
            "insttCode": "3220000",
            "insttNm": "서울특별시 강남구"
          },
          {
            "fcltyKnd": "초등학교",
            "trgetFcltyNm": "왕북초등학교",
            "rdnmadr": "서울특별시 강남구 광평로31길 74",
            "lnmadr": "null",
            "latitude": "37.4863299033",
            "hardness": "127.086039",
            "longitude": "127.086039",
            "institutionNm": "서울특별시 강남구청",
            "cmptncPolcsttnNm": "수서경찰서",
            "cctvYn": "Y",
            "cctvNumber": "3",
            "prtcareaRw": "9",
            "referenceDate": "2019-12-20",
            "insttCode": "3220000",
            "insttNm": "서울특별시 강남구"
          },
          {
            "fcltyKnd": "초등학교",
            "trgetFcltyNm": "개포초등학교",
            "rdnmadr": "서울특별시 강남구 영동대로3길 45",
            "lnmadr": "null",
            "latitude": "37.4868054401",
            "hardness": "127.0699765891",
            "longitude": "127.0699765891",
            "institutionNm": "서울특별시 강남구청",
            "cmptncPolcsttnNm": "수서경찰서",
            "cctvYn": "Y",
            "cctvNumber": "1",
            "prtcareaRw": "15",
            "referenceDate": "2019-12-20",
            "insttCode": "3220000",
            "insttNm": "서울특별시 강남구"
          },
          {
            "fcltyKnd": "초등학교",
            "trgetFcltyNm": "대청초등학교",
            "rdnmadr": "서울특별시 강남구 양재대로55길 28",
            "lnmadr": "null",
            "latitude": "37.493117",
            "hardness": "127.0877676116",
            "longitude": "127.0877676116",
            "institutionNm": "서울특별시 강남구청",
            "cmptncPolcsttnNm": "수서경찰서",
            "cctvYn": "Y",
            "cctvNumber": "4",
            "prtcareaRw": "14.7",
            "referenceDate": "2019-12-20",
            "insttCode": "3220000",
            "insttNm": "서울특별시 강남구"
          },
          {
            "fcltyKnd": "초등학교",
            "trgetFcltyNm": "대치초등학교",
            "rdnmadr": "서울특별시 강남구 양재천로 363",
            "lnmadr": "null",
            "latitude": "37.4912787899",
            "hardness": "127.0621965791",
            "longitude": "127.0621965791",
            "institutionNm": "서울특별시 강남구청",
            "cmptncPolcsttnNm": "수서경찰서",
            "cctvYn": "Y",
            "cctvNumber": "3",
            "prtcareaRw": "8.8",
            "referenceDate": "2019-12-20",
            "insttCode": "3220000",
            "insttNm": "서울특별시 강남구"
          },
          {
            "fcltyKnd": "초등학교",
            "trgetFcltyNm": "양전초등학교",
            "rdnmadr": "서울특별시 강남구 개포로 513",
            "lnmadr": "null",
            "latitude": "37.4902836561",
            "hardness": "127.069478",
            "longitude": "127.069478",
            "institutionNm": "서울특별시 강남구청",
            "cmptncPolcsttnNm": "수서경찰서",
            "cctvYn": "Y",
            "cctvNumber": "4",
            "prtcareaRw": "15",
            "referenceDate": "2019-12-20",
            "insttCode": "3220000",
            "insttNm": "서울특별시 강남구"
          },
          {
            "fcltyKnd": "초등학교",
            "trgetFcltyNm": "세명초등학교",
            "rdnmadr": "서울특별시 강남구 자곡로 55",
            "lnmadr": "null",
            "latitude": "37.468857",
            "hardness": "127.0910762245",
            "longitude": "127.0910762245",
            "institutionNm": "서울특별시 강남구청",
            "cmptncPolcsttnNm": "수서경찰서",
            "cctvYn": "Y",
            "cctvNumber": "2",
            "prtcareaRw": "25",
            "referenceDate": "2019-12-20",
            "insttCode": "3220000",
            "insttNm": "서울특별시 강남구"
          },
          {
            "fcltyKnd": "어린이집",
            "trgetFcltyNm": "신사어린이집",
            "rdnmadr": "서울특별시 강남구 도산대로56길 14",
            "lnmadr": "null",
            "latitude": "37.5221207444",
            "hardness": "127.0401134152",
            "longitude": "127.0401134152",
            "institutionNm": "서울특별시 강남구청",
            "cmptncPolcsttnNm": "강남경찰서",
            "cctvYn": "Y",
            "cctvNumber": "1",
            "prtcareaRw": "6",
            "referenceDate": "2019-12-20",
            "insttCode": "3220000",
            "insttNm": "서울특별시 강남구"
          },
          {
            "fcltyKnd": "어린이집",
            "trgetFcltyNm": "보미나어린이집",
            "rdnmadr": "서울특별시 강남구 학동로20길 25",
            "lnmadr": "null",
            "latitude": "37.5115030798",
            "hardness": "127.0285346272",
            "longitude": "127.0285346272",
            "institutionNm": "서울특별시 강남구청",
            "cmptncPolcsttnNm": "강남경찰서",
            "cctvYn": "Y",
            "cctvNumber": "1",
            "prtcareaRw": "8",
            "referenceDate": "2019-12-20",
            "insttCode": "3220000",
            "insttNm": "서울특별시 강남구"
          },
          {
            "fcltyKnd": "어린이집",
            "trgetFcltyNm": "청담어린이집",
            "rdnmadr": "서울특별시 강남구 도산대로56길 14",
            "lnmadr": "null",
            "latitude": "37.5221207444",
            "hardness": "127.0401134152",
            "longitude": "127.0401134152",
            "institutionNm": "서울특별시 강남구청",
            "cmptncPolcsttnNm": "강남경찰서",
            "cctvYn": "Y",
            "cctvNumber": "1",
            "prtcareaRw": "6",
            "referenceDate": "2019-12-20",
            "insttCode": "3220000",
            "insttNm": "서울특별시 강남구"
          },
          {
            "fcltyKnd": "어린이집",
            "trgetFcltyNm": "역삼어린이집",
            "rdnmadr": "서울특별시 강남구 테헤란로22길 46",
            "lnmadr": "null",
            "latitude": "37.497106",
            "hardness": "127.035679",
            "longitude": "127.035679",
            "institutionNm": "서울특별시 강남구청",
            "cmptncPolcsttnNm": "수서경찰서",
            "cctvYn": "Y",
            "cctvNumber": "1",
            "prtcareaRw": "6",
            "referenceDate": "2019-12-20",
            "insttCode": "3220000",
            "insttNm": "서울특별시 강남구"
          },
          {
            "fcltyKnd": "어린이집",
            "trgetFcltyNm": "선우어린이집",
            "rdnmadr": "서울특별시 강남구 도곡로18길 9",
            "lnmadr": "null",
            "latitude": "37.490733",
            "hardness": "127.0385090573",
            "longitude": "127.0385090573",
            "institutionNm": "서울특별시 강남구청",
            "cmptncPolcsttnNm": "수서경찰서",
            "cctvYn": "Y",
            "cctvNumber": "1",
            "prtcareaRw": "6",
            "referenceDate": "2019-12-20",
            "insttCode": "3220000",
            "insttNm": "서울특별시 강남구"
          },
          {
            "fcltyKnd": "어린이집",
            "trgetFcltyNm": "개포어린이집",
            "rdnmadr": "서울특별시 강남구 영동대로3길",
            "lnmadr": "null",
            "latitude": "37.487954",
            "hardness": "127.073674",
            "longitude": "127.073674",
            "institutionNm": "서울특별시 강남구청",
            "cmptncPolcsttnNm": "수서경찰서",
            "cctvYn": "Y",
            "cctvNumber": "1",
            "prtcareaRw": "12",
            "referenceDate": "2019-12-20",
            "insttCode": "3220000",
            "insttNm": "서울특별시 강남구"
          },
          {
            "fcltyKnd": "어린이집",
            "trgetFcltyNm": "수서어린이집",
            "rdnmadr": "서울특별시 강남구 광평로 242",
            "lnmadr": "null",
            "latitude": "37.486135",
            "hardness": "127.099054",
            "longitude": "127.099054",
            "institutionNm": "서울특별시 강남구청",
            "cmptncPolcsttnNm": "수서경찰서",
            "cctvYn": "Y",
            "cctvNumber": "1",
            "prtcareaRw": "8",
            "referenceDate": "2019-12-20",
            "insttCode": "3220000",
            "insttNm": "서울특별시 강남구"
          },
          {
            "fcltyKnd": "어린이집",
            "trgetFcltyNm": "일원어린이집",
            "rdnmadr": "서울특별시 강남구 광평로3길 9",
            "lnmadr": "null",
            "latitude": "37.483221",
            "hardness": "127.078254",
            "longitude": "127.078254",
            "institutionNm": "서울특별시 강남구청",
            "cmptncPolcsttnNm": "수서경찰서",
            "cctvYn": "Y",
            "cctvNumber": "2",
            "prtcareaRw": "8",
            "referenceDate": "2019-12-20",
            "insttCode": "3220000",
            "insttNm": "서울특별시 강남구"
          },
          {
            "fcltyKnd": "어린이집",
            "trgetFcltyNm": "압구정어린이집",
            "rdnmadr": "서울특별시 강남구 언주로 157길 8",
            "lnmadr": "null",
            "latitude": "37.523923",
            "hardness": "127.0322634719",
            "longitude": "127.0322634719",
            "institutionNm": "서울특별시 강남구청",
            "cmptncPolcsttnNm": "강남경찰서",
            "cctvYn": "Y",
            "cctvNumber": "1",
            "prtcareaRw": "6",
            "referenceDate": "2019-12-20",
            "insttCode": "3220000",
            "insttNm": "서울특별시 강남구"
          }
        ],
        "totalCount": "105",
        "numOfRows": "104",
        "pageNo": "1"
      }
    }
  }