package kr.or.bit;

import java.text.SimpleDateFormat;
import java.util.Calendar;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Reservation.java
//  @ Date : 2020-03-25
//  @ Author : 
//
//

public class Reservation { //예약 
    
    //random도 여기서

    private String customId; //회원 아이디
    private String date; //예매 일자
    private int price; //관람료
    private int num; //예매번호
    //public List reservation = new ArrayList();
    //비밀번호?
    //좌석?
    //공연 종류?
    
    Calendar calendar = Calendar.getInstance();
    SimpleDateFormat simpledateformat = new SimpleDateFormat("yyyy년MM월dd일HH시mm분");
    
    
    
    public void reservationBallet1(String customId) {
    	//reservation.add(new Reservation());
    	this.customId = customId;
    	this.date = simpledateformat.format(calendar.getTime());
    	this.num = (int)(Math.random()*100000)+500000;
    	this.price = 30000;
    }
    
    public void reservationBallet2(String customId) {
    	this.customId = customId;
    	this.date = simpledateformat.format(calendar.getTime());
    	this.num = (int)(Math.random()*100000)+500000;
    	this.price = 30000;
    }
    
    public String getCustomId() {
        return customId;
    }
    public String getDate() {
        return date;
    }
    public int getPrice() {
        return price;
    }
    
    public void setNum(int num) {
        this.num = num;
    }
    
    
    public int getNum() {
        return num;
    }

	@Override
	public String toString() {
		return "Reservation [customId=" + customId + ", date=" + date + ", price=" + price + ", num=" + num
				+ ", calendar=" + calendar + ", simpledateformat=" + simpledateformat + "]";
	}
    
    
    
}//Reservation End